### ISSUE TITLE
Upgrade from OrangeHRM 3.0.1 to 4.10.1 DB update fails

### ISSUE THREAD

**Issue by jdb5** [orangehrm/orangehrm#1293]
**Environment details**
OrangeHRM version: 3.0.1 to 4.10.1 upgrade
OrangeHRM source: https://sourceforge.net/projects/orangehrm/files/stable/4.10.1/orangehrm-4.10.1.zip/download
Platform: Linux usm21.siteground.biz 3.12.18-clouder0 #2 SMP PREEMPT Mon Mar 7 20:55:37 EET 2022 x86_64 x86_64 x86_64 GNU/Linux
PHP version: Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.29, Copyright (c), by Zend Technologies
Database and version: MySQL 5.7.32-35-log - Source distribution
Web server: Apache & Nginx

If applicable:
Browser: Chrome on Windows 10-64bit, Version 101.0.4951.67 (Official Build) (64-bit)

**Describe the bug**
2022-May-20 19:18:37 : MySQL Error: Subquery returns more than 1 row. 
Query: SET @performance_menu_id := (SELECT `id` FROM ohrm_menu_item WHERE `menu_title` = 'Performance' AND `level` = 1);

**To Reproduce**
Happens after clicking "Start" on the database upgrade, fails aroun 15%

**Expected behavior**
A successful DB upgrade 100%

**What do you see instead:**
2022-May-20 19:18:37 : MySQL Error: Subquery returns more than 1 row. 
Query: SET @performance_menu_id := (SELECT `id` FROM ohrm_menu_item WHERE `menu_title` = 'Performance' AND `level` = 1);

StackTrace:#0 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/lib/utility/UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2022-May-20 19:...', true)
#1 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask61.php(368): UpgradeUtility->executeSql('SET @performanc...')
#2 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/modules/upgrade/actions/dbChangeControlAction.class.php(30): SchemaIncrementTask61->execute()
#3 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#4 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#5 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#6 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/lib/filter/ActionFilter.php(14): sfFilterChain->execute()
#8 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(685): sfFilterChain->execute()
#12 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#13 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/symfony/lib/vendor/friendsofsymfony1/symfony1/lib/util/sfContext.class.php(179): sfFrontWebController->dispatch()
#14 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/web/index.php(13): sfContext->dispatch()
#15 {main}
2022-May-20 19:18:37 : MySQL Error: Subquery returns more than 1 row. 
Query: SET @performance_menu_id:= (SELECT id FROM ohrm_menu_item where menu_title = 'Performance');

StackTrace:#0 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/lib/utility/UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2022-May-20 19:...', true)
#1 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask61.php(368): UpgradeUtility->executeSql('SET @performanc...')
#2 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/modules/upgrade/actions/dbChangeControlAction.class.php(30): SchemaIncrementTask61->execute()
#3 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#4 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#5 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#6 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/apps/upgrader/lib/filter/ActionFilter.php(14): sfFilterChain->execute()
#8 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(685): sfFilterChain->execute()
#12 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/cache/upgrader/prod/config/config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#13 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/symfony/lib/vendor/friendsofsymfony1/symfony1/lib/util/sfContext.class.php(179): sfFrontWebController->dispatch()
#14 /home/customer/www/hr.MY_DOMAIN.com/public_html/orangehrm-4.10/upgrader/web/index.php(13): sfContext->dispatch()
#15 {main}

If issue related to installation:
- src/log/installer.log
- logInsatall.log

If issue related to any other
- src/log/orangehrm.log 

**Screenshots**

**Additional context**

**Comment by jdb5** [comment]
**I'm not sure if this is a good fix, but it seems to have worked for me.**

I've solved this, for me by modifing orangehrm-4.10.1/upgrader/apps/upgrader/lib/schemaIncrementTasks/SchemaIncrementTask61.php

Adding LIMIT 1 as shown below to the lines below.

176 $sql[] = "SET @performance_module_id := (SELECT id FROM ohrm_module WHERE name = 'performance' LIMIT 1)";
278 $sql[] = "SET @performance_menu_id := (SELECT `id` FROM ohrm_menu_item WHERE `menu_title` = 'Performance' AND `level` = 1 LIMIT 1);";
317 $sql[] = "SET @performance_menu_id:= (SELECT id FROM ohrm_menu_item where menu_title = 'Performance' LIMIT 1);";
