### ISSUE TITLE
Any version above 4.10.1 (5.0-5.1) not installing on xampp on windows 10

### ISSUE THREAD

**Issue by kvacha13** [orangehrm/orangehrm#1408]
**Environment details**
OrangeHRM version: 5.0-5.1
OrangeHRM source: tried both releases build from [Sourceforge](https://sourceforge.net/projects/orangehrm) and Github
Platform: 64-bit (Windows 11), 
PHP version: PHP 7.4.10 (cli) (built: Sep  1 2020 16:52:39) ( ZTS Visual C++ 2017 x64 ), Zend Engine v3.4.0
Database and version: mysql  Ver 15.1 Distrib 10.4.14-MariaDB, for Win64 (AMD64),
Web server:   Apache 2.4.46

If applicable:
Browser: tried both Chrome, Edge
**Describe the bug**
Please describe what the bug is.
Following installation wizard. After setting all the inputs and starting the installation, the process is stuck on "Applying database changes". 
**To Reproduce**
1. Download version 5.0 or 5.1. Extract zip to apache colder (my case: E:\xampp\htdocs ). 
2. From chrome browser in an address bar enter the orangehrm folder location: 127.0.0.1:8080/orangehrm  (in my case xampp is listening 8080 port)

**Expected behavior**
Installation to finish.

**What do you see instead:**
the Process is stuck on Applying database changes (see attached printscreen). 

If issue related to installation:
- src/log/installer.log:
installer.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `hs_hr_emp_member_detail_ibfk_1`; check that it exists [] []
[2022-07-31T17:21:07.816840+02:00] installer.ERROR: #0 E:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1768): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #1 E:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1707): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #2 E:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1147): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'ALTER TABLE hs_...', Array, Array) #3 E:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Schema\AbstractSchemaManager.php(1204): Doctrine\DBAL\Connection->executeStatement('ALTER TABLE hs_...') #4 E:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Schema\AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql('ALTER TABLE hs_...') #5 E:\xampp\htdocs\orangehrm\installer\Util\V1\SchemaHelper.php(145): Doctrine\DBAL\Schema\AbstractSchemaManager->alterTable(Object(Doctrine\DBAL\Schema\TableDiff)) #6 E:\xampp\htdocs\orangehrm\installer\Migration\V4_1_1\Migration.php(34): OrangeHRM\Installer\Util\V1\SchemaHelper->dropForeignKeys('hs_hr_emp_membe...', Array) #7 E:\xampp\htdocs\orangehrm\installer\Util\AppSetupUtility.php(516): OrangeHRM\Installer\Migration\V4_1_1\Migration->up() #8 E:\xampp\htdocs\orangehrm\installer\Util\AppSetupUtility.php(506): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration('OrangeHRM\\Insta...') #9 E:\xampp\htdocs\orangehrm\installer\Controller\Upgrader\Api\MigrationAPI.php(47): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor('4.1.1') #10 E:\xampp\htdocs\orangehrm\installer\Controller\AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost(Object(OrangeHRM\Framework\Http\Request)) #11 E:\xampp\htdocs\orangehrm\installer\Controller\AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute(Object(OrangeHRM\Framework\Http\Request)) #12 E:\xampp\htdocs\orangehrm\src\vendor\symfony\http-kernel\HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle(Object(OrangeHRM\Framework\Http\Request)) #13 E:\xampp\htdocs\orangehrm\src\vendor\symfony\http-kernel\HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(OrangeHRM\Framework\Http\Request), 1) #14 E:\xampp\htdocs\orangehrm\installer\Framework\HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle(Object(OrangeHRM\Framework\Http\Request), 1, true) #15 E:\xampp\htdocs\orangehrm\installer\index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #16 {main} [] []

- logInsatall.log

If issue related to any other
- src/log/orangehrm.log 

**Screenshots**

**Additional context**
The version 4.9.1 was installed successfully in the same environment. The version 5.1 also was successfully installed on Ubuntu 20.04.
![orangehrm](https://user-images.githubusercontent.com/8162633/182034990-dfc7a394-e1cc-4636-9f24-c6a34bf70266.png)

**Comment by ghYura** [comment]
@kvacha13 Excuse me, do you have demo DB dump, the same as for online demo version was used, maybe?

**Comment by kvacha13** [comment]
@ghYura Sorry for the delayed reply. What exactly are you looking for?

**Comment by kvacha13** [comment]
Unfortunately, only installation files I have are from git: https://github.com/orangehrm/orangehrm/releases

**Comment by fahmiegerton** [comment]
Same thing to me, but I'm on WAMP.NET. And I think it's either something wrong with query or else.

Here my log :

```
[2022-09-08T12:56:00.225128+08:00] installer.INFO: Matched route "{route}". {"route":"api_installer_migration","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\MigrationAPI::handle","_route":"api_installer_migration"},"request_uri":"http://192.168.1.202:89/installer/index.php/installer/api/installation/migration","method":"POST"} []
[2022-09-08T12:56:04.347282+08:00] installer.INFO: Instance details: {"os":{"os":"Windows NT","release_name":"10.0","version_info":"build 20348 (Windows Server 2016)"},"php":{"version":"7.4.30"},"mysql":{"client_version":"mysqlnd 7.4.30","server_version":"5.5.5-10.6.5-MariaDB","conn_type":"localhost via TCP\/IP"},"server":"Apache\/2.4.54 (Win64) OpenSSL\/1.1.1p mod_fcgid\/2.3.10-dev","ohrm":{"version":"5.1"}} [] []
[2022-09-08T12:56:04.628308+08:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `orenhrm`.`ohrm_menu_item`.`parent_id` at row 1 [] []
[2022-09-08T12:56:04.628454+08:00] installer.ERROR: #0 C:\Wamp.NET\sites\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #1 C:\Wamp.NET\sites\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #2 C:\Wamp.NET\sites\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'INSERT INTO ohr...', Array, Array) #3 C:\Wamp.NET\sites\orangehrm\src\vendor\doctrine\dbal\src\Query\QueryBuilder.php(310): Doctrine\DBAL\Connection->executeQuery('INSERT INTO ohr...', Array, Array) #4 C:\Wamp.NET\sites\orangehrm\installer\Migration\V4_0\Migration.php(114): Doctrine\DBAL\Query\QueryBuilder->executeQuery() #5 C:\Wamp.NET\sites\orangehrm\installer\Util\AppSetupUtility.php(523): OrangeHRM\Installer\Migration\V4_0\Migration->up() #6 C:\Wamp.NET\sites\orangehrm\installer\Util\AppSetupUtility.php(513): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration('OrangeHRM\\Insta...') #7 C:\Wamp.NET\sites\orangehrm\installer\Controller\Upgrader\Api\MigrationAPI.php(47): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor('4.0') #8 C:\Wamp.NET\sites\orangehrm\installer\Controller\AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost(Object(OrangeHRM\Framework\Http\Request)) #9 C:\Wamp.NET\sites\orangehrm\installer\Controller\AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute(Object(OrangeHRM\Framework\Http\Request)) #10 C:\Wamp.NET\sites\orangehrm\src\vendor\symfony\http-kernel\HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle(Object(OrangeHRM\Framework\Http\Request)) #11 C:\Wamp.NET\sites\orangehrm\src\vendor\symfony\http-kernel\HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(OrangeHRM\Framework\Http\Request), 1) #12 C:\Wamp.NET\sites\orangehrm\installer\Framework\HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle(Object(OrangeHRM\Framework\Http\Request), 1, true) #13 C:\Wamp.NET\sites\orangehrm\installer\index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #14 {main} [] []
```

Anyone would able to help? Thank you

**Comment by fahmiegerton** [comment]
```
#4 C:\Wamp.NET\sites\orangehrm\installer\Migration\V4_0\Migration.php(114): Doctrine\DBAL\Query\QueryBuilder->executeQuery()
```

I notice it used the version 4 folder, why didn't it use the version 5?

**Comment by RajithaKumara** [comment]
Hi @kvacha13 @fahmiegerton 
Can I know the exact xampp/ wamp application versions?
