### ISSUE TITLE
installation start over agian

### ISSUE THREAD

**Issue by hansdeweerd** [orangehrm/orangehrm#1453]
**Environment details**
OrangeHRM version: 5.1
OrangeHRM source: Release build from 2022-07-25
Platform: Linux Synology 4.4.180+ 
PHP version: 7.4
Database and version:  MariaDB 10.3.32
Web server: Apache 2.2.34

If applicable:
Browser: Chrome

**Describe the bug**
if the installation is complete it start over a again. i am trying to install it on a synology nas.

if i look in the logs of apache server i get this error

[2022-09-17T13:50:56.980225+02:00] installer.INFO: Matched route "{route}". {"route":"installer_complete","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\InstallerCompleteController::handle","_route":"installer_complete"},"request_uri":"https://192.168.1.125/installer/index.php/installer/complete","method":"GET"} []
[2022-09-17T13:50:57.001302+02:00] installer.INFO: OrangeHRM 5.1 status: false [] []
[2022-09-17T13:50:57.068291+02:00] installer.INFO: Matched route "{route}". {"route":"api_installer_migration","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\MigrationAPI::handle","_route":"api_installer_migration"},"request_uri":"https://192.168.1.125/installer/index.php/installer/api/installation/migration","method":"POST"} []
[2022-09-17T13:50:57.139025+02:00] installer.ERROR: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) [] []
[2022-09-17T13:50:57.139189+02:00] installer.ERROR: #0 /volume1/web/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), NULL) #1 /volume1/web/src/vendor/doctrine/dbal/src/Connection.php(1757): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), NULL) #2 /volume1/web/src/vendor/doctrine/dbal/src/Connection.php(343): Doctrine\DBAL\Connection->convertException(Object(Doctrine\DBAL\Driver\PDO\Exception)) #3 /volume1/web/src/vendor/doctrine/dbal/src/Connection.php(405): Doctrine\DBAL\Connection->connect() #4 /volume1/web/src/vendor/doctrine/dbal/src/Connection.php(367): Doctrine\DBAL\Connection->getDatabasePlatformVersion() #5 /volume1/web/src/vendor/doctrine/dbal/src/Connection.php(284): Doctrine\DBAL\Connection->detectDatabasePlatform() #6 /volume1/web/installer/Util/Connection.php(52): Doctrine\DBAL\Connection->getDatabasePlatform() #7 /volume1/web/installer/Util/Connection.php(69): OrangeHRM\Installer\Util\Connection->__construct() #8 /volume1/web/installer/Util/V1/AbstractMigration.php(47): OrangeHRM\Installer\Util\Connection::getConnection() #9 /volume1/web/installer/Util/V1/AbstractMigration.php(64): OrangeHRM\Installer\Util\V1\AbstractMigration->getConnection() #10 /volume1/web/installer/Migration/V4_0/Migration.php(32): OrangeHRM\Installer\Util\V1\AbstractMigration->getSchemaHelper() #11 /volume1/web/installer/Util/AppSetupUtility.php(523): OrangeHRM\Installer\Migration\V4_0\Migration->up() #12 /volume1/web/installer/Util/AppSetupUtility.php(513): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration('OrangeHRM\\Insta...') #13 /volume1/web/installer/Controller/Upgrader/Api/MigrationAPI.php(47): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor('4.0') #14 /volume1/web/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost(Object(OrangeHRM\Framework\Http\Request)) #15 /volume1/web/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute(Object(OrangeHRM\Framework\Http\Request)) #16 /volume1/web/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle(Object(OrangeHRM\Framework\Http\Request)) #17 /volume1/web/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(OrangeHRM\Framework\Http\Request), 1) #18 /volume1/web/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle(Object(OrangeHRM\Framework\Http\Request), 1, true) #19 /volume1/web/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #20 {main} [] []

**Comment by hansdeweerd** [comment]
![step4](https://user-images.githubusercontent.com/77247582/190863798-cdf70c0d-f216-4b04-bfbf-6a840e4d47a9.png)
![step7](https://user-images.githubusercontent.com/77247582/190863799-7210ff0f-e4e8-4644-a1ec-936925575c0d.png)
![step8fail](https://user-images.githubusercontent.com/77247582/190863800-6d1cc938-2d22-4ede-942d-29f1c9a06620.png)

after trying again i get a error at step 8.

**Comment by fahmiegerton** [comment]
same as me, any solution on this?

**Comment by hansdeweerd** [comment]
this issue seem related to issue #1438?

**Comment by hansdeweerd** [comment]
does some one have a solution??

**Comment by RajithaKumara** [comment]
Hi @hansdeweerd , @fahmiegerton 
Please have a look on this answer https://github.com/orangehrm/orangehrm/issues/1344#issuecomment-1290351168

**Comment by HenrysCat** [comment]
Still same problem for me with Docker install.
Debian 11.5, PHP 8.1.11, MariaDB 10.4, OHRM 5.2
Where is /src/log/installer.log in Docker environment?
