### ISSUE TITLE
Connection refused [] []

### ISSUE THREAD

**Issue by kw3rln** [orangehrm/orangehrm#1471]
**Environment details**
OrangeHRM version: 5.1
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: Linux vps-dff46b35 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PHP version: PHP 8.1.10 (cli) (built: Sep 18 2022 10:26:02) (NTS)
Database and version: MySQL 5.7, MariaDB 10.2
Web server: Apache 2.4

If applicable:
Browser: [Chrome,]

**Describe the bug**
![image](https://user-images.githubusercontent.com/114662333/193014445-20b26406-3284-44b5-b871-d522d9aef8c7.png)

```
[2022-09-29T10:17:55.868463+00:00] installer.ERROR: Connection refused [] []
[2022-09-29T10:17:55.868587+00:00] installer.ERROR: #0 /var/www/html/2msolutions/src/vendor/doctrine/orm/lib/Doctrine/ORM/ORMSetup.php(193): Redis->connect() #1 /var/www/html/2msolutions/src/vendor/doctrine/orm/lib/Doctrine/ORM/ORMSetup.php(147): Doctrine\ORM\ORMSetup::createCacheInstance() #2 /var/www/html/2msolutions/src/vendor/doctrine/orm/lib/Doctrine/ORM/ORMSetup.php(42): Doctrine\ORM\ORMSetup::createConfiguration() #3 /var/www/html/2msolutions/src/lib/orm/Doctrine.php(51): Doctrine\ORM\ORMSetup::createAnnotationMetadataConfiguration() #4 /var/www/html/2msolutions/src/lib/orm/Doctrine.php(104): OrangeHRM\ORM\Doctrine->__construct() #5 /var/www/html/2msolutions/src/lib/orm/Doctrine.php(114): OrangeHRM\ORM\Doctrine::getInstance() #6 /var/www/html/2msolutions/installer/Controller/Upgrader/Api/ConfigFileAPI.php(67): OrangeHRM\ORM\Doctrine::getEntityManager() #7 /var/www/html/2msolutions/installer/Controller/Installer/Api/ConfigFileAPI.php(47): OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI->handlePost() #8 /var/www/html/2msolutions/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Installer\Api\ConfigFileAPI->handlePost() #9 /var/www/html/2msolutions/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #10 /var/www/html/2msolutions/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #11 /var/www/html/2msolutions/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #12 /var/www/html/2msolutions/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #13 /var/www/html/2msolutions/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #14 {main} [] []
[2022-09-29T10:24:22.942555+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_clean_up_install","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\CleanUpInstallAPI::handle","_route":"api_installer_clean_up_install"},"request_uri":"http://51.68.198.2/2msolutions/installer/index.php/installer/api/clean-up-install","method":"POST"} []
[2022-09-29T10:24:40.169406+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_clean_up_install","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\CleanUpInstallAPI::handle","_route":"api_installer_clean_up_install"},"request_uri":"http://51.68.198.2/2msolutions/installer/index.php/installer/api/clean-up-install","method":"POST"} []
```

**Comment by RajithaKumara** [comment]
Hi @kw3rln,
Thanks for providing error log.
Seems in your environment `redis` PHP extension is installed/enabled. Is there any possibility to disable `redis` extension for the OrangeHRM application. 
This seems a bug in the application as Doctrine try to setup cache with `redis`. Meantime we will fix this bug in next release.

**Comment by kw3rln** [comment]
Hello @RajithaKumara
I have another problem with the old version of orangehrm. I tried to update to the new version but I completely broke the old one. ( the update has failed )
in /symfony/logs: 
[30-Sep-2022 10:11:02 Europe/Berlin] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'h.key' in 'field list'. Failing Query: "SELECT h.`key` AS h__0, h.value AS h__1, h.`key` AS h__0, h.value AS h__1 FROM hs_hr_config h"
is there any way to fix ?

Thanks

**Comment by RajithaKumara** [comment]
In the upgrader it's recommend to backup current database. Or use copy of the production database. Once you run the upgrader the database will be compatible only with the latest version (the OrangeHRM version you used to upgrade). 
So your old OrangeHRM application (4.x) will no longer be usable, because version to version database schema may change.

**Comment by RajithaKumara** [comment]
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).

**Comment by tngiabeor** [comment]
Hi @RajithaKumara 
I am unable to complete this step due to errors in Zip extension status and LDAP extension status. Can you help me fix it? 
Thank you so much
![error](https://github.com/orangehrm/orangehrm/assets/146937939/a30fbcb4-20ed-4d29-b160-a1193bed4d63)

**Comment by devishke-orange** [comment]
Hi @tngiabeor 

You need to install the relevant PHP extensions in order to continue with the installation.

Example: https://stackoverflow.com/questions/33869521/how-can-i-enable-php-extension-intl/34850253#34850253
