### ISSUE TITLE
Request failed with status code 500. For more details check the error log in /src/log/installer.log file

### ISSUE THREAD

**Issue by prcctv** [orangehrm/orangehrm#1504]
**Environment details**
OrangeHRM version: [5.2]
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: 64-bit (Ubuntu server 22.04.1)
PHP version: output of `php -7.4`
Database and version: [ MariaDB 10.6]
Web server: [Apache 2.4 ]
Browser: [Chrome]

**Describe the bug**
"Request failed with status code 500. For more details check the error log in /src/log/installer.log file"
When the installation process reaches 99%（Creating configuration files）

- src/log/installer.log
- logInsatall.log
[2022-10-21T10:57:48.586963+00:00] installer.ERROR: Client error: `POST https://ospenguin.orangehrm.com/` resulted in a `400 Bad Request` response [] []
[2022-10-21T10:57:48.587028+00:00] installer.ERROR: #0 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create() #1 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler() #3 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run() #5 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #7 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait() #10 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request() #11 /var/www/html/orangehrm/installer/Util/Service/DataRegistrationService.php(57): GuzzleHttp\Client->post() #12 /var/www/html/orangehrm/installer/Controller/Installer/Api/InstallerDataRegistrationAPI.php(53): OrangeHRM\Installer\Util\Service\DataRegistrationService->sendRegistrationData() #13 /var/www/html/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Installer\Api\InstallerDataRegistrationAPI->handlePost() #14 /var/www/html/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #15 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #16 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #17 /var/www/html/orangehrm/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #18 /var/www/html/orangehrm/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #19 {main} [] []

[2022-10-21T10:58:07.156973+00:00] installer.ERROR: Client error: `POST https://ospenguin.orangehrm.com/` resulted in a `400 Bad Request` response [] []
[2022-10-21T10:58:07.157049+00:00] installer.ERROR: #0 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create() #1 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler() #3 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run() #5 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #7 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait() #10 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request() #11 /var/www/html/orangehrm/installer/Util/Service/DataRegistrationService.php(57): GuzzleHttp\Client->post() #12 /var/www/html/orangehrm/installer/Util/DataRegistrationUtility.php(259): OrangeHRM\Installer\Util\Service\DataRegistrationService->sendRegistrationData() #13 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/ConfigFileAPI.php(88): OrangeHRM\Installer\Util\DataRegistrationUtility->sendRegistrationDataOnFailure() #14 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/ConfigFileAPI.php(64): OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI->sendRegistrationData() #15 /var/www/html/orangehrm/installer/Controller/Installer/Api/ConfigFileAPI.php(66): OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI->handlePost() #16 /var/www/html/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Installer\Api\ConfigFileAPI->handlePost() #17 /var/www/html/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #18 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #19 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #20 /var/www/html/orangehrm/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #21 /var/www/html/orangehrm/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #22 {main} [] []
[2022-10-21T10:58:07.479207+00:00] installer.ERROR: Client error: `POST https://ospenguin.orangehrm.com/` resulted in a `400 Bad Request` response [] []
[2022-10-21T10:58:07.479291+00:00] installer.ERROR: #0 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create() #1 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}() #2 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler() #3 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run() #5 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #7 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /var/www/html/orangehrm/src/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait() #10 /var/www/html/orangehrm/src/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request() #11 /var/www/html/orangehrm/installer/Util/Service/DataRegistrationService.php(57): GuzzleHttp\Client->post() #12 /var/www/html/orangehrm/installer/Util/DataRegistrationUtility.php(284): OrangeHRM\Installer\Util\Service\DataRegistrationService->sendRegistrationData() #13 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/ConfigFileAPI.php(92): OrangeHRM\Installer\Util\DataRegistrationUtility->sendRegistrationDataOnSuccess() #14 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/ConfigFileAPI.php(64): OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI->sendRegistrationData() #15 /var/www/html/orangehrm/installer/Controller/Installer/Api/ConfigFileAPI.php(66): OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI->handlePost() #16 /var/www/html/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Installer\Api\ConfigFileAPI->handlePost() #17 /var/www/html/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #18 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #19 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #20 /var/www/html/orangehrm/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #21 /var/www/html/orangehrm/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #22 {main} [] []
[2022-10-21T10:58:07.480633+00:00] installer.ERROR: Malformed parameter "url". [] []
[2022-10-21T10:58:07.480679+00:00] installer.ERROR: #0 /var/www/html/orangehrm/src/vendor/doctrine/dbal/src/DriverManager.php(195): Doctrine\DBAL\DriverManager::parseDatabaseUrl() #1 /var/www/html/orangehrm/src/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(987): Doctrine\DBAL\DriverManager::getConnection() #2 /var/www/html/orangehrm/src/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(966): Doctrine\ORM\EntityManager::createConnection() #3 /var/www/html/orangehrm/src/lib/orm/Doctrine.php(76): Doctrine\ORM\EntityManager::create() #4 /var/www/html/orangehrm/src/lib/orm/Doctrine.php(104): OrangeHRM\ORM\Doctrine->__construct() #5 /var/www/html/orangehrm/src/lib/orm/Doctrine.php(114): OrangeHRM\ORM\Doctrine::getInstance() #6 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/ConfigFileAPI.php(67): OrangeHRM\ORM\Doctrine::getEntityManager() #7 /var/www/html/orangehrm/installer/Controller/Installer/Api/ConfigFileAPI.php(66): OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI->handlePost() #8 /var/www/html/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Installer\Api\ConfigFileAPI->handlePost() #9 /var/www/html/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #10 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #11 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #12 /var/www/html/orangehrm/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #13 /var/www/html/orangehrm/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #14 {main} [] []

**Comment by prcctv** [comment]
this has been solved perfectly
 #[1501]( https://github.com/orangehrm/orangehrm/issues/1501).

**Comment by RajithaKumara** [comment]
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).
