### ISSUE TITLE
Log-in takes 5 minutes to complete [OHRM 5.2]

### ISSUE THREAD

**Issue by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [orangehrm/orangehrm#1523]
**Environment details**
OrangeHRM version: 5.2 (Image MD5: 7c65683ee0025865c42e6049f47723c5)
OrangeHRM source: Release build from Dockerhub 
Platform: Docker
PHP version:  php.net/distributions/php-8.1.11.tar.xz
Database and version: 1:10.9.3+maria~ubu2204
Web server: built-in web server of Docker-Image 

If applicable:
Browser: Edge (version information in screenshots)

**Describe the bug**
Log-In takes about 5 minutes to complete, everything else after that is normal / fast

**To Reproduce**
Log-in and out (also via "incognito"-mode in browser)
Restart container

**Expected behavior**
"Normal" log-in time ... couple seconds

**What do you see instead:**
loading / static page

If issue related to installation:
---

If issue related to any other
---
![Screenshot 2022-11-07 174926](https://user-images.githubusercontent.com/117673153/200378832-d9f6d222-4d3a-46e0-8def-1029d7ab1959.png)
![Screenshot 2022-11-07 175726](https://user-images.githubusercontent.com/117673153/200378844-d0ae03ee-1ff6-4285-a711-c1d3c7fa1eb3.png)

**Screenshots**
Screenshot of docker and browser log

**Additional context**
---

**Comment by RajithaKumara** [comment]
Hi @t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq ,
Did you configure LDAP authentication?

**Comment by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [comment]
Hi,
i dont have LDAP enabled
![Screenshot 2022-11-08 102555](https://user-images.githubusercontent.com/117673153/200526851-299974dc-a802-4bcd-807e-93a5fc7efe06.png)

**Comment by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [comment]
> Hi, i dont have LDAP enabled ![Screenshot 2022-11-08 102555](https://user-images.githubusercontent.com/117673153/200526851-299974dc-a802-4bcd-807e-93a5fc7efe06.png)

do you need more / different information?

**Comment by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [comment]
![image](https://user-images.githubusercontent.com/117673153/203383631-09162542-cbf1-4246-b8ad-be8456be2b8d.png)
Hello,

the problem must be located @ "web/index.php/auth/**validate**" but i dont understand your source code well enough to get to the root of the problem. I run different services on different ports on the same server. Maybe the validate function validates more than it should, so it takes more time? In the screenshot you can see that more cookie data from different services is shown.

**Comment by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [comment]
1) Docker Container (Orangehrm) on a Debain Host (Portainer)
2) Now it is but the problem was present before i added the proxy
3) each login for any user, yes
4) yes
5) yes other browser on different machienes

In the logs i found the following while loging in:
[2022-11-23T10:21:51.827065+00:00] orangehrm.ERROR: cURL error 28: Failed to connect to ospenguin.orangehrm.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://ospenguin.orangehrm.com [] []
[2022-11-23T10:21:51.827363+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #4 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #5 /var/www/html/src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #6 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #7 /var/www/html/src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #8 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #9 /var/www/html/src/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #10 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #11 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array) #12 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array) #13 /var/www/html/src/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', '', Array) #14 /var/www/html/src/plugins/orangehrmCorePlugin/Registration/Service/RegistrationAPIClientService.php(56): GuzzleHttp\Client->post('', Array) #15 /var/www/html/src/plugins/orangehrmCorePlugin/Registration/Processor/AbstractRegistrationEventProcessor.php(209): OrangeHRM\Core\Registration\Service\RegistrationAPIClientService->publishData(Array) #16 /var/www/html/src/plugins/orangehrmCorePlugin/Registration/Subscriber/RegistrationEventPublishSubscriber.php(55): OrangeHRM\Core\Registration\Processor\AbstractRegistrationEventProcessor->publishRegistrationEvents() #17 /var/www/html/src/vendor/symfony/event-dispatcher/EventDispatcher.php(230): OrangeHRM\Core\Registration\Subscriber\RegistrationEventPublishSubscriber->onTerminateEvent(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...', Object(OrangeHRM\Framework\Event\EventDispatcher)) #18 /var/www/html/src/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.terminat...', Object(Symfony\Component\HttpKernel\Event\TerminateEvent)) #19 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...') #20 /var/www/html/web/index.php(48): Symfony\Component\HttpKernel\HttpKernel->terminate(Object(OrangeHRM\Framework\Http\Request), Object(OrangeHRM\Framework\Http\RedirectResponse)) #21 {main} [] []
[2022-11-23T10:24:02.896950+00:00] orangehrm.ERROR: cURL error 28: Failed to connect to ospenguin.orangehrm.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://ospenguin.orangehrm.com [] []
[2022-11-23T10:24:02.897157+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #4 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #5 /var/www/html/src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #6 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #7 /var/www/html/src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #8 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #9 /var/www/html/src/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #10 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #11 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array) #12 /var/www/html/src/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array) #13 /var/www/html/src/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request('POST', '', Array) #14 /var/www/html/src/plugins/orangehrmCorePlugin/Registration/Service/RegistrationAPIClientService.php(56): GuzzleHttp\Client->post('', Array) #15 /var/www/html/src/plugins/orangehrmCorePlugin/Registration/Processor/AbstractRegistrationEventProcessor.php(209): OrangeHRM\Core\Registration\Service\RegistrationAPIClientService->publishData(Array) #16 /var/www/html/src/plugins/orangehrmCorePlugin/Registration/Subscriber/RegistrationEventPublishSubscriber.php(55): OrangeHRM\Core\Registration\Processor\AbstractRegistrationEventProcessor->publishRegistrationEvents() #17 /var/www/html/src/vendor/symfony/event-dispatcher/EventDispatcher.php(230): OrangeHRM\Core\Registration\Subscriber\RegistrationEventPublishSubscriber->onTerminateEvent(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...', Object(OrangeHRM\Framework\Event\EventDispatcher)) #18 /var/www/html/src/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.terminat...', Object(Symfony\Component\HttpKernel\Event\TerminateEvent)) #19 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(94): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...') #20 /var/www/html/web/index.php(48): Symfony\Component\HttpKernel\HttpKernel->terminate(Object(OrangeHRM\Framework\Http\Request), Object(OrangeHRM\Framework\Http\RedirectResponse)) #21 {main} 

Why is it neccessary to connect to some url (ospenguin.orangehrm.com) while loging in? My server has no access to the www.
Can you direct me to your source code that is connected to the "/auth/validate" process? Maybe i can find out why it takes ~5 min. to validate/authenticate on login vs ~300 ms to authenticate via password on the admin panel.

Thanks for responding!

**Comment by RajithaKumara** [comment]
Hi @t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq ,
We could reproduce this issue, and will be fixed in OrangeHRM 5.3 release, planned to release end of December.
Thanks for reporting this issue.

**Comment by RajithaKumara** [comment]
This issue was fixed in OrangeHRM 5.3. Get the latest build [here](https://sourceforge.net/projects/orangehrm/).

**Comment by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [comment]
can confirm that its fixed now.
thank you and happy new year!
