### ISSUE TITLE
Applying database changes

### ISSUE THREAD

**Issue by paulchike** [orangehrm/orangehrm#1536]
**Environment details**
OrangeHRM version: [5.0]
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows), or Docker
PHP version: output of `php -v`
Database and version: [e.g. MySQL 5.7, MariaDB 10.2]
Web server: [e.g. Apache 2.4, Nginx 1.4]

If applicable:
Browser: Chrome

[2022-11-16T01:17:50.589981+00:00] installer.ERROR: Wrong parameters for Doctrine\DBAL\Driver\PDO\Exception([string $message [, long $code [, Throwable $previous = NULL]]]) [] []
[2022-11-16T01:17:50.590103+00:00] installer.ERROR: #0 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/AbstractException.php(34): Exception->__construct() #1 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/PDO/Exception.php(26): Doctrine\DBAL\Driver\AbstractException->__construct() #2 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/PDO/Result.php(109): Doctrine\DBAL\Driver\PDO\Exception::new() #3 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/PDO/Result.php(49): Doctrine\DBAL\Driver\PDO\Result->fetch() #4 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Result.php(75): Doctrine\DBAL\Driver\PDO\Result->fetchOne() #5 /home/hrms/public_html/installer/Migration/V4_5_0/Migration.php(85): Doctrine\DBAL\Result->fetchOne() #6 /home/hrms/public_html/installer/Util/AppSetupUtility.php(516): OrangeHRM\Installer\Migration\V4_5_0\Migration->up() #7 /home/hrms/public_html/installer/Util/AppSetupUtility.php(506): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration() #8 /home/hrms/public_html/installer/Controller/Upgrader/Api/MigrationAPI.php(47): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor() #9 /home/hrms/public_html/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost() #10 /home/hrms/public_html/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #11 /home/hrms/public_html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #12 /home/hrms/public_html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /home/hrms/public_html/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /home/hrms/public_html/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #15 {main} [] []

**To Reproduce**
Installation of Orangehrm
**Expected behavior**
It gets stuck on Applying database changes

**What do you see instead:**
[2022-11-16T01:17:50.589981+00:00] installer.ERROR: Wrong parameters for Doctrine\DBAL\Driver\PDO\Exception([string $message [, long $code [, Throwable $previous = NULL]]]) [] []
[2022-11-16T01:17:50.590103+00:00] installer.ERROR: #0 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/AbstractException.php(34): Exception->__construct() #1 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/PDO/Exception.php(26): Doctrine\DBAL\Driver\AbstractException->__construct() #2 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/PDO/Result.php(109): Doctrine\DBAL\Driver\PDO\Exception::new() #3 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Driver/PDO/Result.php(49): Doctrine\DBAL\Driver\PDO\Result->fetch() #4 /home/hrms/public_html/src/vendor/doctrine/dbal/src/Result.php(75): Doctrine\DBAL\Driver\PDO\Result->fetchOne() #5 /home/hrms/public_html/installer/Migration/V4_5_0/Migration.php(85): Doctrine\DBAL\Result->fetchOne() #6 /home/hrms/public_html/installer/Util/AppSetupUtility.php(516): OrangeHRM\Installer\Migration\V4_5_0\Migration->up() #7 /home/hrms/public_html/installer/Util/AppSetupUtility.php(506): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration() #8 /home/hrms/public_html/installer/Controller/Upgrader/Api/MigrationAPI.php(47): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor() #9 /home/hrms/public_html/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost() #10 /home/hrms/public_html/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #11 /home/hrms/public_html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #12 /home/hrms/public_html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /home/hrms/public_html/installer/Framework/HttpKernel.php(224): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /home/hrms/public_html/installer/index.php(64): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #15 {main} [] []

If issue related to installation:
- src/log/installer.log
- logInsatall.log

If issue related to any other
- src/log/orangehrm.log 

**Screenshots**

**Additional context**
[Applying database.txt](https://github.com/orangehrm/orangehrm/files/10017397/Applying.database.txt)

**Comment by RajithaKumara** [comment]
Hi @paulchike ,
This is a bug in 5.0 release already reported #1299.
Please use the least OrangeHRM version from [here](https://sourceforge.net/projects/orangehrm/files/latest/download)

If you really want to use 5.0 you have to apply [this patch](https://github.com/orangehrm/orangehrm/issues/1299#issuecomment-1139382507)

**Comment by paulchike** [comment]
Thanks for your help @RajithaKumara, I have been able to install the application. However, I am facing a challenge of editing the files, when I edit to remove or add a field in the code using FTP, it doesn't effect on the front interface. Any clue what I may be doing wrong?

Thanks again.
