### ISSUE TITLE
An exception occurred in the driver: could not find driver

### ISSUE THREAD

**Issue by psiborgtech** [orangehrm/orangehrm#1539]
Have the error in step two itself

```
[2022-11-17T11:04:29.387864+00:00] installer.INFO: Matched route "{route}". {"route":"installer_home","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\HomeController::handle","_route":"installer_home"},"request_uri":"http://3.110.119.147/orangehrm-5.>
[2022-11-17T11:04:29.732795+00:00] installer.INFO: Matched route "{route}". {"route":"installer_welcome","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\WelcomeController::handle","_route":"installer_welcome"},"request_uri":"http://3.110.119.147/ora>
[2022-11-17T11:04:46.429083+00:00] installer.INFO: Matched route "{route}". {"route":"installer_licence_acceptance","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\LicenceAcceptanceController::handle","_route":"installer_licence_acceptanc>
[2022-11-17T11:04:51.281796+00:00] installer.INFO: Matched route "{route}". {"route":"installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\DatabaseConfigController::handle","_route":"installer_database_config"},"requ>
[2022-11-17T11:04:51.419359+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"}>
[2022-11-17T11:24:15.988040+00:00] installer.INFO: Matched route "{route}". {"route":"installer_home","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\HomeController::handle","_route":"installer_home"},"request_uri":"http://3.110.119.147/orangehrm-5.>
[2022-11-17T11:24:16.515092+00:00] installer.INFO: Matched route "{route}". {"route":"installer_welcome","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\WelcomeController::handle","_route":"installer_welcome"},"request_uri":"http://3.110.119.147/ora>
[2022-11-17T11:24:20.371902+00:00] installer.INFO: Matched route "{route}". {"route":"installer_licence_acceptance","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\LicenceAcceptanceController::handle","_route":"installer_licence_acceptanc>
[2022-11-17T11:24:24.025778+00:00] installer.INFO: Matched route "{route}". {"route":"installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\DatabaseConfigController::handle","_route":"installer_database_config"},"requ>
[2022-11-17T11:24:24.193707+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"}>
[2022-11-17T11:27:05.304342+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"}>
[2022-11-17T11:27:05.341552+00:00] installer.ERROR: An exception occurred in the driver: could not find driver [] []
[2022-11-17T11:27:05.341646+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(>
[2022-11-17T11:55:43.064571+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"}>
[2022-11-17T11:55:43.065414+00:00] installer.ERROR: An exception occurred in the driver: could not find driver [] []
[2022-11-17T11:55:43.065459+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(>
[2022-11-17T11:56:24.377690+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"}>
[2022-11-17T11:56:24.400759+00:00] installer.ERROR: An exception occurred in the driver: could not find driver [] []
[2022-11-17T11:56:24.400813+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(>
[2022-11-17T12:02:15.002003+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"}>
[2022-11-17T12:02:15.026373+00:00] installer.ERROR: An exception occurred in the driver: could not find driver [] []
[2022-11-17T12:02:15.026448+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/orangehrm-5.2/src/vendor/doctrine/dbal/src/Connection.php(>
```

![HRM](https://user-images.githubusercontent.com/52708851/202446057-006dcbce-93aa-4500-8e2e-6988a6c16f1f.png)

**Comment by Super-Chama** [comment]
Hi @psiborgtech looks like some php dependencies are unmet. you need to install [php-mysql](https://www.php.net/manual/en/book.mysqlnd.php) extension according to your server environment and php version.

For debian based distributions like ubuntu you can install it by running `sudo apt install php-mysql` or `sudo apt install php81-mysql`
