### ISSUE TITLE
Unexpected Error Occured

### ISSUE THREAD

**Issue by paulchike** [orangehrm/orangehrm#1542]
**Environment details**
OrangeHRM version: 5.2
OrangeHRM source: Release build from [Sourceforge](https://sourceforge.net/projects/orangehrm) or Git clone
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows), or Docker
PHP version: output of `php -8.1`
Database and version: MySQL 5.7
Web server: Apache 2.4

If applicable:
Browser:  Chrome

**Describe the bug**
I keep seeing "Unexpected Error Occur" when I click on **Leave** menu or **Dashboard** menu

**To Reproduce**
Click on the 
**Leave**
Please describe what you expected to happen.
Not sure what is happening, I keep seeing Unexpected Error Occured

**What do you see instead:**
The error message

If issue related to any other
[2022-11-20T00:04:56.473200+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:04:56.473421+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(914): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(115): Doctrine\ORM\AbstractQuery->getScalarResult() #9 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(545): Doctrine\ORM\Tools\Pagination\Paginator->count() #10 /var/www/html/src/plugins/orangehrmDashboardPlugin/Dto/ActionSummary/PendingLeaveRequestSummary.php(72): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequestsCount() #11 /var/www/html/src/plugins/orangehrmDashboardPlugin/Dto/ActionSummary/PendingAction.php(46): OrangeHRM\Dashboard\Dto\ActionSummary\PendingLeaveRequestSummary->getPendingActionCount() #12 /var/www/html/src/plugins/orangehrmDashboardPlugin/Api/EmployeeActionSummaryAPI.php(89): OrangeHRM\Dashboard\Dto\ActionSummary\PendingAction->generateActionSummary() #13 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(83): OrangeHRM\Dashboard\Api\EmployeeActionSummaryAPI->getOne() #14 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #15 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #16 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #17 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #18 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #19 {main} [] []
[2022-11-20T00:05:35.381839+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:05:35.382017+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(914): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(115): Doctrine\ORM\AbstractQuery->getScalarResult() #9 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(545): Doctrine\ORM\Tools\Pagination\Paginator->count() #10 /var/www/html/src/plugins/orangehrmDashboardPlugin/Dto/ActionSummary/PendingLeaveRequestSummary.php(72): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequestsCount() #11 /var/www/html/src/plugins/orangehrmDashboardPlugin/Dto/ActionSummary/PendingAction.php(46): OrangeHRM\Dashboard\Dto\ActionSummary\PendingLeaveRequestSummary->getPendingActionCount() #12 /var/www/html/src/plugins/orangehrmDashboardPlugin/Api/EmployeeActionSummaryAPI.php(89): OrangeHRM\Dashboard\Dto\ActionSummary\PendingAction->generateActionSummary() #13 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(83): OrangeHRM\Dashboard\Api\EmployeeActionSummaryAPI->getOne() #14 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #15 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #16 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #17 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #18 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #19 {main} [] []
[2022-11-20T00:11:50.014588+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:11:50.014717+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(535): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveRequestAPI.php(119): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequests() #9 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(77): OrangeHRM\Leave\Api\EmployeeLeaveRequestAPI->getAll() #10 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #15 {main} [] []
[2022-11-20T00:11:56.209011+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:11:56.209194+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(535): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveRequestAPI.php(119): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequests() #9 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(77): OrangeHRM\Leave\Api\EmployeeLeaveRequestAPI->getAll() #10 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #15 {main} [] []
[2022-11-20T00:12:34.289896+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:12:34.290033+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(914): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(115): Doctrine\ORM\AbstractQuery->getScalarResult() #9 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(545): Doctrine\ORM\Tools\Pagination\Paginator->count() #10 /var/www/html/src/plugins/orangehrmDashboardPlugin/Dto/ActionSummary/PendingLeaveRequestSummary.php(72): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequestsCount() #11 /var/www/html/src/plugins/orangehrmDashboardPlugin/Dto/ActionSummary/PendingAction.php(46): OrangeHRM\Dashboard\Dto\ActionSummary\PendingLeaveRequestSummary->getPendingActionCount() #12 /var/www/html/src/plugins/orangehrmDashboardPlugin/Api/EmployeeActionSummaryAPI.php(89): OrangeHRM\Dashboard\Dto\ActionSummary\PendingAction->generateActionSummary() #13 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(83): OrangeHRM\Dashboard\Api\EmployeeActionSummaryAPI->getOne() #14 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #15 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #16 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #17 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #18 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #19 {main} [] []
[2022-11-20T00:12:43.521271+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:12:43.521439+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(535): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveRequestAPI.php(119): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequests() #9 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(77): OrangeHRM\Leave\Api\EmployeeLeaveRequestAPI->getAll() #10 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #15 {main} [] []
[2022-11-20T00:19:09.043600+00:00] orangehrm.ERROR:  [] []
[2022-11-20T00:19:09.045687+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/symfony/event-dispatcher/EventDispatcher.php(230): OrangeHRM\Authentication\Subscriber\AuthenticationSubscriber->onControllerEvent() #1 /var/www/html/src/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #2 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #3 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #4 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #5 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #6 {main} [] []
[2022-11-20T00:20:33.628433+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:20:33.628591+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(535): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveRequestAPI.php(119): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequests() #9 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(77): OrangeHRM\Leave\Api\EmployeeLeaveRequestAPI->getAll() #10 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #15 {main} [] []
[2022-11-20T00:27:56.461674+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:27:56.461810+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(535): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/plugins/orangehrmLeavePlugin/Api/MyLeaveRequestAPI.php(84): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequests() #9 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(77): OrangeHRM\Leave\Api\MyLeaveRequestAPI->getAll() #10 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #15 {main} [] []
[2022-11-20T00:28:20.415078+00:00] orangehrm.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'pauhrms.o1_.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by [] []
[2022-11-20T00:28:20.415266+00:00] orangehrm.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/plugins/orangehrmLeavePlugin/Dao/LeaveRequestDao.php(535): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/plugins/orangehrmLeavePlugin/Api/EmployeeLeaveRequestAPI.php(119): OrangeHRM\Leave\Dao\LeaveRequestDao->getLeaveRequests() #9 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(77): OrangeHRM\Leave\Api\EmployeeLeaveRequestAPI->getAll() #10 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(146): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handleGetRequest() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #15 {main} [] []

**Screenshots**

**Additional context**

**Comment by RajithaKumara** [comment]
Hi @paulchike
Thanks for detailed explanation.
Please have a look on 2nd step of this answer https://github.com/orangehrm/orangehrm/issues/1521#issuecomment-1305050958

**Comment by paulchike** [comment]
> Thanks @RajithaKumara
