### ISSUE TITLE
LDAP fails to sync users

### ISSUE THREAD

**Issue by selaschuk** [orangehrm/orangehrm#1614]
### OrangeHRM version

5.3

### Environment details

- OrangeHRM source: Sourceforge
- Platform: Ubuntu 22
- PHP version: 8.1
- Database and version: Mysql 5.7
- Web server: Apache 2.4

### Describe the bug

When trying to sync users via LDAP, pressing Sync Now generates the error:
Error - Please check the settings for your LDAP configuration
OHM ldap.log shows the following:
General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=' [] []

### Relevant log output

```shell
src/log/ldap.log

[2023-02-10T19:57:18.988819+00:00] LDAP.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(31): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1188): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1142): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(930): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/src/plugins/orangehrmLDAPAuthenticationPlugin/Dao/LDAPDao.php(111): Doctrine\ORM\AbstractQuery->getOneOrNullResult() #9 /var/www/html/src/plugins/orangehrmLDAPAuthenticationPlugin/Service/LDAPSyncService.php(235): OrangeHRM\LDAP\Dao\LDAPDao->getAuthProviderByUserUniqueId() #10 /var/www/html/src/plugins/orangehrmLDAPAuthenticationPlugin/Service/LDAPSyncService.php(375): OrangeHRM\LDAP\Service\LDAPSyncService->createSystemUsers() #11 /var/www/html/src/plugins/orangehrmLDAPAuthenticationPlugin/Api/LDAPUserSyncAPI.php(89): OrangeHRM\LDAP\Service\LDAPSyncService->sync() #12 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(113): OrangeHRM\LDAP\Api\LDAPUserSyncAPI->create() #13 /var/www/html/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(150): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handlePostRequest() #14 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #15 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #16 /var/www/html/src/lib/framework/Framework.php(157): Symfony\Component\HttpKernel\HttpKernel->handle() #17 /var/www/html/web/index.php(42): OrangeHRM\Framework\Framework->handleRequest() #18 {main} [] []
[2023-02-10T19:57:24.190849+00:00] LDAP.ERROR: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=' [] []
```

**Comment by eebene** [comment]
Experiencing the same issue, it is caused only when **User Unique ID Attribute** is set to objectGUID against an AD.

**Comment by RajithaKumara** [comment]
Hi @eebene ,
Can I know your environment details also? Mainly database version.
Also, want to know one extra thing, did you install the fresh 5.3 version or upgraded from 4.x version to 5.3?

**Comment by eebene** [comment]
Hi @RajithaKumara ,

Platform: Debian 11
Database and version: Mysql  Ver 8.0.32
Fresh install of 5.3
PHP version: 8.1
Web server: Apache 2.4.56


This may help you:  if I use any text or int field it works fine (i.e sAMAccountName, employeeID, userPrincipalName),  just not binary field (i.e objectGUID, objectSid)

I hope this is helpful.

Thank you for your prompt response.

**Comment by RajithaKumara** [comment]
Thanks for the info.
If you don't mind, could you please provide sample values for `objectGUID` and `objectSid` also?

**Comment by eebene** [comment]
Hi @RajithaKumara,

Please see attachment for requested info.

![Screenshot 2023-04-17 6 53 23 PM](https://user-images.githubusercontent.com/111053697/232627520-f7c65256-39d8-466a-b50c-8af9215cf724.png)
