### ISSUE TITLE
Upgrading to 5.4 Error on applying Database Changes

### ISSUE THREAD

**Issue by jgriffithsuk** [orangehrm/orangehrm#1704]
### OrangeHRM version

5.0

### Environment details

- OrangeHRM source: Sourceforge
- Platform:  ubuntu2.11
- PHP version: 8.1.
- Database and version: 5.5.5-10.6.12-MariaDB
- Web server: Apache
- Browser: Firefox

### Describe the bug

When upgrading I get these errors

[2023-06-02T10:38:20.483294+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'apiv2_performance_kpi' for key 'name' [] []
[2023-06-02T10:38:20.483340+00:00] installer.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doct

### Relevant log output

```shell
[2023-06-02T10:38:20.483294+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'apiv2_performance_kpi' for key 'name' [] []
[2023-06-02T10:38:20.483340+00:00] installer.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doct
```

**Comment by RajithaKumara** [comment]
Hi @jgriffithsuk 
Any possibility try[ latest release](https://sourceforge.net/projects/orangehrm/files/latest/download) (5.4 at the moment)
It seems we added the performance module (for 5.x) in 5.1 version, can you double-check OrangeHRM version?

**Comment by jgriffithsuk** [comment]
Hi

I have tried 5.4 that was the errors I got,

Also 5.1 wouldn’t install

**Comment by devishke-orange** [comment]
Hi @devambrose, @jgriffithsuk 

Were you able to upgrade OrangeHRM afterwards?

**Comment by jgriffithsuk** [comment]
No we were unable too

To many changes / errors in the Database
