### ISSUE TITLE
Upgrade to version 5.5 error on applying database changes

### ISSUE THREAD

**Issue by mrdanleey** [orangehrm/orangehrm#1716]
### OrangeHRM version

5.4

### Environment details

- OrangeHRM source: SourceForce
- Platform: Ubuntu Server
- PHP version: 8
- Database and version: MariaDB 10.3.38 
- Web server: Apache 2
- Browser: All browsers

### Describe the bug

I'm getting a error when upgrading to version 5.5:

[2023-07-10T09:39:29.442040+02:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`stageregistratie`.`ohrm_i18n_translate`, CONSTRAINT `langStringId` FOREIGN KEY (`lang_string_id`) REFERENCES `ohrm_i18n_lang_string` (`id`)) [] []
[2023-07-10T09:39:29.442126+02:00] installer.ERROR: #0 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Query/QueryBuilder.php(310): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/orangehrm/installer/Util/V1/LanguageHelper.php(95): Doctrine\DBAL\Query\QueryBuilder->executeQuery() #5 /var/www/orangehrm/installer/Migration/V5_5_0/Migration.php(49): OrangeHRM\Installer\Util\V1\LanguageHelper->deleteLangStringByUnitId() #6 /var/www/orangehrm/installer/Util/AppSetupUtility.php(526): OrangeHRM\Installer\Migration\V5_5_0\Migration->up() #7 /var/www/orangehrm/installer/Util/AppSetupUtility.php(514): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration() #8 /var/www/orangehrm/installer/Controller/Upgrader/Api/MigrationAPI.php(50): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor() #9 /var/www/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost() #10 /var/www/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #11 /var/www/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #12 /var/www/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/orangehrm/installer/Framework/HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/orangehrm/installer/index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #15 {main} [] []

### Relevant log output

```shell
[2023-07-10T09:39:29.442040+02:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`stageregistratie`.`ohrm_i18n_translate`, CONSTRAINT `langStringId` FOREIGN KEY (`lang_string_id`) REFERENCES `ohrm_i18n_lang_string` (`id`)) [] []
[2023-07-10T09:39:29.442126+02:00] installer.ERROR: #0 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/orangehrm/src/vendor/doctrine/dbal/src/Query/QueryBuilder.php(310): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/orangehrm/installer/Util/V1/LanguageHelper.php(95): Doctrine\DBAL\Query\QueryBuilder->executeQuery() #5 /var/www/orangehrm/installer/Migration/V5_5_0/Migration.php(49): OrangeHRM\Installer\Util\V1\LanguageHelper->deleteLangStringByUnitId() #6 /var/www/orangehrm/installer/Util/AppSetupUtility.php(526): OrangeHRM\Installer\Migration\V5_5_0\Migration->up() #7 /var/www/orangehrm/installer/Util/AppSetupUtility.php(514): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration() #8 /var/www/orangehrm/installer/Controller/Upgrader/Api/MigrationAPI.php(50): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor() #9 /var/www/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost() #10 /var/www/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #11 /var/www/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #12 /var/www/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/orangehrm/installer/Framework/HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/orangehrm/installer/index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #15 {main} [] []
```

**Comment by devishke-orange** [comment]
Hi @mrdanleey. The issue is being caused from two particular lang strings that we are deleting in 5.5. It seems that your particular database may contain some translations for these particular lang strings.

For a temporary fix, you can run this query on your database to delete the translations and try upgrading again. Please backup your database just in case.

`DELETE FROM ohrm_i18n_translate WHERE ohrm_i18n_translate.lang_string_id=973 OR ohrm_i18n_translate.lang_string_id=336`

**Comment by devishke-orange** [comment]
Hi @mrdanleey . Did you have any luck upgrading after running the SQL query? If you are facing any difficulties let us know.

**Comment by kavithagurusamy** [comment]
Closing the ticket as no response from the reporter. The solution is given in the thread.
