### ISSUE TITLE
Dockerfile & instruction doesn't work (status code 500 during installation)

### ISSUE THREAD

**Issue by mm86133** [orangehrm/orangehrm#1751]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: docker pull orangehrm/orangehrm
- Platform: windows
- PHP version: from your docker
- Database and version:docker pull mariadb:10.4
- Web server: from your docker
- Browser: any

### Describe the bug

[2023-09-27T14:24:06.123299+00:00] installer.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1163): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1204): Doctrine\DBAL\Connection->executeStatement() #4 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql() #5 /var/www/html/installer/Util/V1/SchemaHelper.php(153): Doctrine\DBAL\Schema\AbstractSchemaManager->alterTable() #6 /var/www/html/installer/Migration/V4_3_3/Migration.php(36): OrangeHRM\Installer\Util\V1\SchemaHelper->changeColumn() #7 /var/www/html/installer/Util/AppSetupUtility.php(526): OrangeHRM\Installer\Migration\V4_3_3\Migration->up() 
#8 /var/www/html/installer/Util/AppSetupUtility.php(514): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration() #9 /var/www/html/installer/Controller/Upgrader/Api/MigrationAPI.php(50): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor() #10 /var/www/html/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost() #11 /var/www/html/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #13 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #14 /var/www/html/installer/Framework/HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle() #15 /var/www/html/installer/index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #16 {main} [] [

### To reproduce

[How to setup web container](https://github.com/orangehrm/orangehrm/wiki/How-to-Install-via-Docker-image#how-to-setup-web-container)
Pull Oranghrm docker image docker pull orangehrm/orangehrm
Run Oranghrm web image docker run -d --name ohrm-web orangehrm/orangehrm
[How to setup db container](https://github.com/orangehrm/orangehrm/wiki/How-to-Install-via-Docker-image#how-to-setup-db-container)
Pull DB docker image docker pull mariadb:10.4
Run Oranghrm web image docker run -d --name ohrm-db -e MYSQL_ROOT_PASSWORD=<pass> mariadb:10.4

Run installation and you'll get that error.

### Expected behavior

It should install 

### Relevant log output

```shell
[2023-09-27T14:24:06.123299+00:00] installer.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1163): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1204): Doctrine\DBAL\Connection->executeStatement() #4 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql() #5 /var/www/html/installer/Util/V1/SchemaHelper.php(153): Doctrine\DBAL\Schema\AbstractSchemaManager->alterTable() #6 /var/www/html/installer/Migration/V4_3_3/Migration.php(36): OrangeHRM\Installer\Util\V1\SchemaHelper->changeColumn() #7 /var/www/html/installer/Util/AppSetupUtility.php(526): OrangeHRM\Installer\Migration\V4_3_3\Migration->up() 
#8 /var/www/html/installer/Util/AppSetupUtility.php(514): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration() #9 /var/www/html/installer/Controller/Upgrader/Api/MigrationAPI.php(50): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor() #10 /var/www/html/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost() #11 /var/www/html/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #13 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #14 /var/www/html/installer/Framework/HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle() #15 /var/www/html/installer/index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #16 {main} [] [
```

**Comment by mm86133** [comment]
The same issue happens to the 5.4 version.

It won't finish the install.

**Comment by mm86133** [comment]
Same issue happens on Ubuntu 18 too.

**Comment by RajithaKumara** [comment]
Hi @mm86133 ,
Thanks for raising this issue with error logs.
I suspect that it's related to #1731 issue.
Is there any possibility for you to try https://github.com/orangehrm/orangehrm/issues/1731#issuecomment-1727583099

Basically, downgrade your MariaDB version by installing MariaDB `10.4.30` using `docker pull mariadb:10.4.30` in [How to setup db container](https://github.com/orangehrm/orangehrm/wiki/How-to-Install-via-Docker-image#how-to-setup-db-container) step.

**Comment by devishke-orange** [comment]
I'm closing this since there has been no activity.
