### ISSUE TITLE
Install fails on "checking db permissions"

### ISSUE THREAD

**Issue by Nortag82** [orangehrm/orangehrm#1761]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: git
- Platform: Ubuntu 22.04.3 LTS
- PHP version: 8.1
- Database and version: 8.0.34-0ubuntu0.22.04.1
- Web server: apache2
- Browser: chrome / edge

### Describe the bug

Getting this:
![image](https://github.com/orangehrm/orangehrm/assets/122754323/b09f1f49-b8a1-47a2-ad9f-194eda7951ed)

tried several things, new db, different user accounts. 

### Relevant log output

```shell
[2023-10-18T11:37:30.978853+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of O>
[2023-10-18T11:37:30.978917+00:00] installer.ERROR: #0 /var/www/html/hrm/orangehrm-5.5/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\Exce>
```

**Comment by devishke-orange** [comment]
Hi  @Nortag82 

Please provide us the full `installer.log` file.

**Comment by Nortag82** [comment]
> Hi @Nortag82
> 
> Please provide us the full `installer.log` file. You can remove any sensitive data from it and upload it.

https://github.com/orangehrm/orangehrm/issues/1761https://github.com/orangehrm/orangehrm/issues/1761[2023-10-18T22:01:54.370511+00:00] installer.INFO: Matched route "{route}>
[2023-10-18T22:01:54.594615+00:00] installer.INFO: Matched route "{route}". {"route":"installer_welcome","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\>
[2023-10-18T22:01:57.991995+00:00] installer.INFO: Matched route "{route}". {"route":"installer_licence_acceptance","route_parameters":{"_controller":"OrangeHRM\\Installer\\>
[2023-10-18T22:02:11.569422+00:00] installer.INFO: Matched route "{route}". {"route":"installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Con>
[2023-10-18T22:02:11.747393+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-10-18T22:02:31.672821+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-10-18T22:02:31.746189+00:00] installer.INFO: Instance details: {"os":{"os":"Linux","release_name":"5.15.0-86-generic","version_info":"#96-Ubuntu SMP Wed Sep 20 08:23:4>
[2023-10-18T22:02:31.984519+00:00] installer.INFO: Matched route "{route}". {"route":"installer_system_check","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contro>
[2023-10-18T22:02:32.182008+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_system_check","route_parameters":{"_controller":"OrangeHRM\\Installer\\Co>
[2023-10-18T22:02:36.112946+00:00] installer.INFO: Matched route "{route}". {"route":"installer_instance_creation","route_parameters":{"_controller":"OrangeHRM\\Installer\\C>
[2023-10-18T22:02:36.277576+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_countries","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contr>
[2023-10-18T22:02:36.469383+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_languages","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contr>
[2023-10-18T22:02:36.652647+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_timezones","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contr>
[2023-10-18T22:02:36.933686+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_instance","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contro>
[2023-10-18T22:03:09.345953+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_instance","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contro>
[2023-10-18T22:03:09.521403+00:00] installer.INFO: Matched route "{route}". {"route":"installer_admin_user_creation","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-10-18T22:03:09.712084+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_admin_user","route_parameters":{"_controller":"OrangeHRM\\Installer\\Cont>
[2023-10-18T22:03:46.058368+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_admin_user","route_parameters":{"_controller":"OrangeHRM\\Installer\\Cont>
[2023-10-18T22:03:46.263609+00:00] installer.INFO: Matched route "{route}". {"route":"installer_confirmation","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contro>
[2023-10-18T22:03:46.482765+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-10-18T22:03:46.648936+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_admin_user","route_parameters":{"_controller":"OrangeHRM\\Installer\\Cont>
[2023-10-18T22:03:48.310528+00:00] installer.INFO: Matched route "{route}". {"route":"installer_process","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\>
[2023-10-18T22:03:48.560507+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_start_registration","route_parameters":{"_controller":"OrangeHRM\\Install>
[2023-10-18T22:03:48.598758+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database","route_parameters":{"_controller":"OrangeHRM\\Installer\\Contro>
[2023-10-18T22:03:48.604166+00:00] installer.INFO: Instance details: {"os":{"os":"Linux","release_name":"5.15.0-86-generic","version_info":"#96-Ubuntu SMP Wed Sep 20 08:23:4>
[2023-10-18T22:03:48.775046+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_pre_migration_check","route_parameters":{"_controller":"OrangeHRM\\Instal>
[2023-10-18T22:03:48.786038+00:00] installer.INFO: Instance details: {"os":{"os":"Linux","release_name":"5.15.0-86-generic","version_info":"#96-Ubuntu SMP Wed Sep 20 08:23:4>
[2023-10-18T22:03:48.954344+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of O>
[2023-10-18T22:03:48.954479+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.5/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\Exceptio>
[2023-11-01T20:42:42.651535+00:00] installer.INFO: Matched route "{route}". {"route":"installer_home","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Ho>
[2023-11-01T20:42:42.762309+00:00] installer.INFO: Matched route "{route}". {"route":"installer_welcome","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\>
[2023-11-01T20:42:45.424744+00:00] installer.INFO: Matched route "{route}". {"route":"installer_licence_acceptance","route_parameters":{"_controller":"OrangeHRM\\Installer\\>
[2023-11-01T20:42:56.902430+00:00] installer.INFO: Matched route "{route}". {"route":"installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Con>
[2023-11-01T20:42:57.016472+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-11-01T20:43:32.505557+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-11-01T20:43:32.549016+00:00] installer.ERROR: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'sjsj'@'localhost' (using password: YE>
[2023-11-01T20:43:32.549090+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.5/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\Exceptio>
[2023-11-01T20:43:53.161916+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-11-01T20:43:53.164712+00:00] installer.ERROR: An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' [] []
[2023-11-01T20:43:53.164811+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.5/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\Exceptio>
[2023-11-01T20:43:59.784870+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\>
[2023-11-01T20:43:59.788906+00:00] installer.ERROR: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'abroot'@'localhost' (using password: >
[2023-11-01T20:43:59.789048+00:00] installer.ERROR: #0 /var/www/html/orangehrm-5.5/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\Exceptio>

**Comment by RajithaKumara** [comment]
Hi @Nortag82,
It seems you are getting this error because you are using invalid credentials for root user or any other database users. 
```
An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'sjsj'@'localhost' (using password: YE>
```
```
An exception occurred in the driver: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' [] []
```
```
An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'abroot'@'localhost' (using password: >
```
```
An exception occurred in the driver: SQLSTATE[HY000] [1044] Access denied for user 'sj'@'localhost' to database 'jau' [] >`
```
Also have a look on [this help article as well](https://starterhelp.orangehrm.com/hc/en-us/articles/5295915003666-OrangeHRM-Starter-Installation-Guide). Also did you change the codebase?
