### ISSUE TITLE
Error installation in database cheking 

### ISSUE THREAD

**Issue by Bennys6** [orangehrm/orangehrm#1773]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: Github
- Platform: linux
- PHP version: 8.2
- Database and version: 10.6
- Web server: apache
- Browser: chrome

### Describe the bug

hy, you can help me. I try to install orange hrm in my own server but stuck in database checking with status 'Request failed with status code 500'. web server and database server developed different server (that is possible or not?) and this is the log I found

[2023-11-23T06:25:17.743358+00:00] installer.ERROR: Invalid result [] []
[2023-11-23T06:25:17.743452+00:00] installer.ERROR: #0 /var/www/html/orangehrm/installer/Util/DatabaseUserPermissionEvaluator.php(376): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalCrudPermission() #1 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/PreMigrationCheck.php(35): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalPrivilegeDatabaseUserPermission() #2 /var/www/html/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\PreMigrationCheck->handlePost() #3 /var/www/html/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #4 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #5 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #6 /var/www/html/orangehrm/installer/Framework/HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle() #7 /var/www/html/orangehrm/installer/index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #8 {main} [] []

and sorry my english is not good

### Relevant log output

```shell
[2023-11-23T06:25:17.743358+00:00] installer.ERROR: Invalid result [] []
[2023-11-23T06:25:17.743452+00:00] installer.ERROR: #0 /var/www/html/orangehrm/installer/Util/DatabaseUserPermissionEvaluator.php(376): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalCrudPermission() #1 /var/www/html/orangehrm/installer/Controller/Upgrader/Api/PreMigrationCheck.php(35): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalPrivilegeDatabaseUserPermission() #2 /var/www/html/orangehrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\PreMigrationCheck->handlePost() #3 /var/www/html/orangehrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #4 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #5 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #6 /var/www/html/orangehrm/installer/Framework/HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle() #7 /var/www/html/orangehrm/installer/index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #8 {main} [] []
```

**Comment by Bluecatzmv** [comment]
the same as you
