### ISSUE TITLE
Request failed with status code 500. For more details check the error log in /src/log/installer.log file

### ISSUE THREAD

**Issue by kumaranshankars** [orangehrm/orangehrm#1778]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source: 5.5
- Platform: Xampp 
- PHP version: 8
- Database and version: 5.7
- Web server: Apache
- Browser: Chrome

![OrangeHRM installation error](https://github.com/orangehrm/orangehrm/assets/143519348/46acc82a-9e62-4c60-9d82-7680efdfb0eb)

### Describe the bug

Getting the above mentioned error during installation.

Error Log is attached

### Relevant log output

```shell
`installer.ERROR: #0 C:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #1 C:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #2 C:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Connection.php(1055): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT COUNT(_o...', Array, Array) #3 C:\xampp\htdocs\orangehrm\src\vendor\doctrine\dbal\src\Query\QueryBuilder.php(310): Doctrine\DBAL\Connection->executeQuery('SELECT COUNT(_o...', Array, Array) #4 C:\xampp\htdocs\orangehrm\installer\Util\DatabaseUserPermissionEvaluator.php(116): Doctrine\DBAL\Query\QueryBuilder->executeQuery() #5 C:\xampp\htdocs\orangehrm\installer\Util\DatabaseUserPermissionEvaluator.php(376): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalCrudPermission() #6 C:\xampp\htdocs\orangehrm\installer\Controller\Upgrader\Api\PreMigrationCheck.php(35): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalPrivilegeDatabaseUserPermission() #7 `C:\xampp\htdocs\orangehrm\installer\Controller\AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\PreMigrationCheck->handlePost(Object(OrangeHRM\Framework\Http\Request)) #8 C:\xampp\htdocs\orangehrm\installer\Controller\AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute(Object(OrangeHRM\Framework\Http\Request)) #9 C:\xampp\htdocs\orangehrm\src\vendor\symfony\http-kernel\HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle(Object(OrangeHRM\Framework\Http\Request)) #10 C:\xampp\htdocs\orangehrm\src\vendor\symfony\http-kernel\HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(OrangeHRM\Framework\Http\Request), 1) #11 C:\xampp\htdocs\orangehrm\installer\Framework\HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle(Object(OrangeHRM\Framework\Http\Request), 1, true) #12 C:\xampp\htdocs\orangehrm\installer\index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #13 {main} [] []
```

**Comment by RajithaKumara** [comment]
Hi @kumaranshankars 
Sorry to hear that you are getting this error. We will further check this, can you send us the full error log. or the line above to the provided log line.
I feel it's due to `sql_mode`, `ONLY_FULL_GROUP_BY` issue, please have a look at this solution https://github.com/orangehrm/orangehrm/issues/1582#issuecomment-1367186952

**Comment by devishke-orange** [comment]
Hi @kumaranshankars,

If you do not want to share your log file here, you can forward it ossupport@orangehrm.com

**Comment by kumaranshankars** [comment]
> Hi @kumaranshankars Sorry to hear that you are getting this error. We will further check this, can you send us the full error log. or the line above to the provided log line. I feel it's due to `sql_mode`, `ONLY_FULL_GROUP_BY` issue, please have a look at this solution [#1582 (comment)](https://github.com/orangehrm/orangehrm/issues/1582#issuecomment-1367186952)

Thanks for your reply, I have fixed this by replacing the Migration.php from the 5.6 which I downloaded from another branch.
