### ISSUE TITLE
Error while installing Request failed with status code 500. For more details check the error log in /src/log/installer.log file

### ISSUE THREAD

**Issue by vvsreerag** [orangehrm/orangehrm#1779]
### OrangeHRM version

5.5

### Environment details

- OrangeHRM source:
- Platform: ubuntu lampp
- PHP version: 8.2
- Database and version:
- Web server:
- Browser:

### Describe the bug

While installing its stopping at Applying database changes and showing the error Request failed with status code 500. For more details check the error log in /src/log/installer.log file how to resolve it ? 
@RajithaKumara  please 

### Relevant log output

```shell
[2023-12-15T15:18:47.519167+01:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'ohrm_job_interview_ibfk_1' of table 'orangehrm.ohrm_job_interview' [] []
[2023-12-15T15:18:47.519431+01:00] installer.ERROR: #0 /opt/lampp/htdocs/gslhrm/src/vendor/doctrine/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #1 /opt/lampp/htdocs/gslhrm/src/vendor/doctrine/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query)) #2 /opt/lampp/htdocs/gslhrm/src/vendor/doctrine/dbal/src/Connection.php(1163): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'ALTER TABLE ohr...', Array, Array) #3 /opt/lampp/htdocs/gslhrm/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1204): Doctrine\DBAL\Connection->executeStatement('ALTER TABLE ohr...') #4 /opt/lampp/htdocs/gslhrm/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql('ALTER TABLE ohr...') #5 /opt/lampp/htdocs/gslhrm/installer/Util/V1/SchemaHelper.php(153): Doctrine\DBAL\Schema\AbstractSchemaManager->alterTable(Object(Doctrine\DBAL\Schema\TableDiff)) #6 /opt/lampp/htdocs/gslhrm/installer/Migration/V4_3_3/Migration.php(54): OrangeHRM\Installer\Util\V1\SchemaHelper->changeColumn('ohrm_job_candid...', 'id', Array) #7 /opt/lampp/htdocs/gslhrm/installer/Util/AppSetupUtility.php(526): OrangeHRM\Installer\Migration\V4_3_3\Migration->up() #8 /opt/lampp/htdocs/gslhrm/installer/Util/AppSetupUtility.php(514): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration('OrangeHRM\\Insta...') #9 /opt/lampp/htdocs/gslhrm/installer/Controller/Upgrader/Api/MigrationAPI.php(50): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor('4.3.3') #10 /opt/lampp/htdocs/gslhrm/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost(Object(OrangeHRM\Framework\Http\Request)) #11 /opt/lampp/htdocs/gslhrm/installer/Controller/AbstractInstallerController.php(85): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute(Object(OrangeHRM\Framework\Http\Request)) #12 /opt/lampp/htdocs/gslhrm/src/vendor/symfony/http-kernel/HttpKernel.php(152): OrangeHRM\Installer\Controller\AbstractInstallerController->handle(Object(OrangeHRM\Framework\Http\Request)) #13 /opt/lampp/htdocs/gslhrm/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(OrangeHRM\Framework\Http\Request), 1) #14 /opt/lampp/htdocs/gslhrm/installer/Framework/HttpKernel.php(244): Symfony\Component\HttpKernel\HttpKernel->handle(Object(OrangeHRM\Framework\Http\Request), 1, true) #15 /opt/lampp/htdocs/gslhrm/installer/index.php(66): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #16 {main} [] []
```

**Comment by devishke-orange** [comment]
HI @vvsreerag 

This is a known issue. Please see https://github.com/orangehrm/orangehrm/issues/1731#issuecomment-1727583099
