### ISSUE TITLE
Unable to add new account after upgrading from 5.5 to 5.6

### ISSUE THREAD

**Issue by abrarreddragon** [orangehrm/orangehrm#1796]
### OrangeHRM version

5.6

### Environment details

- OrangeHRM source:
- Platform:
- PHP version:
- Database and version:
- Web server:
- Browser:

### Describe the bug

I just upgraded from OrangeHRM 5.5 to 5.6 and now all the admin accounts cannot add any new user. Getting error Unauthorized.

### To reproduce

On the server replaced all the files running OrangeHRM 5.5 to 5.6 and try to create a new user / add employee.

### Expected behavior

Getting Unauthorized Error Message

### Relevant log output

```shell
[2024-01-30T11:08:31.603928-08:00] orangehrm.ERROR: Unauthorized [] []
[2024-01-30T11:08:31.605561-08:00] orangehrm.ERROR: #0 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/event-dispatcher/EventDispatcher.php(230): OrangeHRM\Core\Subscriber\ApiAuthorizationSubscriber->onControllerEvent(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...', Object(OrangeHRM\Framework\Event\EventDispatcher)) #1 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.controll...', Object(Symfony\Component\HttpKernel\Event\ControllerEvent)) #2 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/http-kernel/HttpKernel.php(140): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ControllerEvent), 'kernel.controll...') #3 /home/dh_x5gcja/hrm.appfiniti.us/src/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(OrangeHRM\Framework\Http\Request), 1) #4 /home/dh_x5gcja/hrm.appfiniti.us/src/lib/framework/Framework.php(156): Symfony\Component\HttpKernel\HttpKernel->handle(Object(OrangeHRM\Framework\Http\Request), 1, true) #5 /home/dh_x5gcja/hrm.appfiniti.us/web/index.php(41): OrangeHRM\Framework\Framework->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #6 {main} [] []
```

**Comment by devishke-orange** [comment]
Hi @abrarreddragon 

> On the server replaced all the files running OrangeHRM 5.5 to 5.6 and try to create a new user / add employee.

You should not replace the files. Please keep your OrangeHRM 5.5 and 5.6 folders separately. You can follow this guide to upgrade your system: https://starterhelp.orangehrm.com/hc/en-us/articles/6937346912402-OrangeHRM-Starter-Upgrade-Guide-For-5x-versions.

**Comment by devishke-orange** [comment]
Hi @abrarreddragon I hope you were able to solve this issue after following the upgrade guide. I will close this since there has been no activity.
