### ISSUE TITLE
Cannot install OrangeHRM v5.6

### ISSUE THREAD

**Issue by buisontung1995** [orangehrm/orangehrm#1827]
### OrangeHRM version

5.6

### Environment details

- OrangeHRM source: release build from Sourceforge
- Platform: MAC OS Sonoma 14.2.1
- PHP version: 8.2.4
- Database and version: MariaDB 10.4.28
- Web server: Apache 2.4.56
- Browser: Chrome

### Describe the bug

When go to "http://localhost/orangehrm-5.6/installer/index.php", it showed this error
![image](https://github.com/orangehrm/orangehrm/assets/97793313/d41ea00f-1426-44c2-9518-45857938ecb1)

I already set full access for folder "htdocs" also "orangehrm-5.6" where source code located
![image](https://github.com/orangehrm/orangehrm/assets/97793313/2390cfb5-ae79-4270-b861-5a5461b85a9f)
![image](https://github.com/orangehrm/orangehrm/assets/97793313/fac86372-93d5-49fa-997d-e06fdd41550a)


### Relevant log output

```shell
The issue related to installion

[2024-03-22T05:33:57.495128+01:00] installer.ERROR: Failed to write file "/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt": file_put_contents(/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt): Failed to open stream: Permission denied [] []
[2024-03-22T05:33:57.497477+01:00] installer.ERROR: #0 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Util/SystemCheck.php(602): OrangeHRM\Framework\Filesystem\Filesystem->dumpFile('/var/folders/m6...', '/var/folders/m6...') #1 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(190): OrangeHRM\Installer\Util\SystemCheck->checkWritePermission('/var/folders/m6...') #2 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(241): OrangeHRM\Installer\Framework\HttpKernel->configureSession(Object(OrangeHRM\Framework\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #4 {main} [] []
[2024-03-22T05:34:55.737933+01:00] installer.ERROR: Failed to write file "/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt": file_put_contents(/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt): Failed to open stream: Permission denied [] []
[2024-03-22T05:34:55.740595+01:00] installer.ERROR: #0 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Util/SystemCheck.php(602): OrangeHRM\Framework\Filesystem\Filesystem->dumpFile('/var/folders/m6...', '/var/folders/m6...') #1 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(190): OrangeHRM\Installer\Util\SystemCheck->checkWritePermission('/var/folders/m6...') #2 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(241): OrangeHRM\Installer\Framework\HttpKernel->configureSession(Object(OrangeHRM\Framework\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #4 {main} [] []
[2024-03-22T07:55:48.127935+01:00] installer.ERROR: Failed to write file "/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt": file_put_contents(/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt): Failed to open stream: Permission denied [] []
[2024-03-22T07:55:48.130846+01:00] installer.ERROR: #0 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Util/SystemCheck.php(602): OrangeHRM\Framework\Filesystem\Filesystem->dumpFile('/var/folders/m6...', '/var/folders/m6...') #1 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(190): OrangeHRM\Installer\Util\SystemCheck->checkWritePermission('/var/folders/m6...') #2 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(241): OrangeHRM\Installer\Framework\HttpKernel->configureSession(Object(OrangeHRM\Framework\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #4 {main} [] []
[2024-03-22T07:55:48.676822+01:00] installer.ERROR: Failed to write file "/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt": file_put_contents(/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt): Failed to open stream: Permission denied [] []
[2024-03-22T07:55:48.677599+01:00] installer.ERROR: #0 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Util/SystemCheck.php(602): OrangeHRM\Framework\Filesystem\Filesystem->dumpFile('/var/folders/m6...', '/var/folders/m6...') #1 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(190): OrangeHRM\Installer\Util\SystemCheck->checkWritePermission('/var/folders/m6...') #2 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(241): OrangeHRM\Installer\Framework\HttpKernel->configureSession(Object(OrangeHRM\Framework\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #4 {main} [] []
[2024-03-22T07:59:26.273687+01:00] installer.ERROR: Failed to write file "/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt": file_put_contents(/var/folders/m6/1t8855fn32dggnf9db6_12nw0000gn/T/_temp.txt): Failed to open stream: Permission denied [] []
[2024-03-22T07:59:26.275972+01:00] installer.ERROR: #0 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Util/SystemCheck.php(602): OrangeHRM\Framework\Filesystem\Filesystem->dumpFile('/var/folders/m6...', '/var/folders/m6...') #1 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(190): OrangeHRM\Installer\Util\SystemCheck->checkWritePermission('/var/folders/m6...') #2 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/Framework/HttpKernel.php(241): OrangeHRM\Installer\Framework\HttpKernel->configureSession(Object(OrangeHRM\Framework\Http\Request)) #3 /Applications/XAMPP/xamppfiles/htdocs/orangehrm-5.6/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest(Object(OrangeHRM\Framework\Http\Request)) #4 {main} [] []
```

**Comment by devishke-orange** [comment]
Hi @buisontung1995,

Can you try changing the session storage directory as detailed here: https://github.com/orangehrm/orangehrm/issues/1750#issuecomment-1740291114 (the second method)

**Comment by devishke-orange** [comment]
Hi @buisontung1995,

Did you have any luck changing the session directory?

**Comment by devishke-orange** [comment]
I'm closing this since there has been no response. Feel free to reopen this if you are still facing the issue.
