### ISSUE TITLE
Bump MySQL Version to 8.4

### ISSUE THREAD

**Issue by sonic-sw** [orangehrm/orangehrm#1853]
Dear OrangeHRM Team,

our mysql server was updated to 8.4 and now fails to install a new instance of OrangeHRM (latest docker image).
After altering the /var/www/html/installer/config/system_requirements.php to pass the system validation check, the installer stops at 98% with the following message:

```
[2024-06-06T09:01:42.118633+00:00] installer.INFO: Instance details: {"os":{"os":"Linux","release_name":"6.1.75+","version_info":"#1 SMP PREEMPT_DYNAMIC Fri Apr  5 14:32:23 UTC 2024"},"php":{"version":"8.3.4"},"mysql":{"client_version":"mysqlnd 8.3.4","server_version":"8.4.0","conn_type":"mysql-primary.data-stores via TCP\/IP"},"server":"Apache\/2.4.57 (Debian)","ohrm":{"version":"5.6.1"}} [] []
[2024-06-06T09:01:42.150830+00:00] installer.INFO: set_time_limit: success [] []
[2024-06-06T09:01:55.710445+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 6125 Failed to add the foreign key constraint. Missing unique key for constraint 'ohrm_project_activity_ibfk_1' in the referenced table 'ohrm_project' [] []
[2024-06-06T09:01:55.710587+00:00] installer.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1943): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1885): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1213): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/installer/Migration/V3_3_3/Migration.php(42): Doctrine\DBAL\Connection->executeStatement() #4 /var/www/html/installer/Migration/V3_3_3/Migration.php(27): OrangeHRM\Installer\Migration\V3_3_3\Migration->execQueries() #5 /var/www/html/installer/Util/AppSetupUtility.php(542): OrangeHRM\Installer\Migration\V3_3_3\Migration->up() #6 /var/www/html/installer/Util/AppSetupUtility.php(518): OrangeHRM\Installer\Util\AppSetupUtility->_runMigration() #7 /var/www/html/installer/Controller/Upgrader/Api/MigrationAPI.php(49): OrangeHRM\Installer\Util\AppSetupUtility->runMigrationFor() #8 /var/www/html/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI->handlePost() #9 /var/www/html/installer/Controller/AbstractInstallerController.php(84): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #10 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(163): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #12 /var/www/html/installer/Framework/HttpKernel.php(243): Symfony\Component\HttpKernel\HttpKernel->handle() #13 /var/www/html/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #14 {main} [] []
```

**Comment by devishke-orange** [comment]
Hi @sonic-sw 

We have fixed this for our upcoming 5.7 release. I have linked the relevant PR above.

**Comment by sonic-sw** [comment]
@devishke-orange Thanks 
Will be looking out for the new image!
