### ISSUE TITLE
orangehrm.ERROR: No route found, Not able to open `/leave` route 

### ISSUE THREAD

**Issue by rbale3108** [orangehrm/orangehrm#1859]
### OrangeHRM version

5.6.1

### Environment details

- OrangeHRM source: 5.6.1
- Platform: Ubuntu 22.04
- PHP version: 8.1
- Database and version: Mysql 8.0.30
- Web server: Apache
- Browser: chrome

### Describe the bug

I have installed OrangeHRM on the Ubuntu server. For Admin login everything is working fine, but when I'm using Employee login I'm not able to open `/leave routes` example below URL, 
`http://192.168.0.136/orangehrm/web/index.php/leave/showLeavePeriodNotDefinedWarning`

error screenshot:

![image](https://github.com/orangehrm/orangehrm/assets/91748984/e99c5a17-427f-41f0-a043-9fdf00a78c21)

in `/var/log/apache2/access.log` I'm getting a 404 status code.
```
192.168.0.94 - - [29/Jun/2024:12:50:00 +0000] "GET /orangehrm/web/index.php/leave/showLeavePeriodNotDefinedWarning HTTP/1.1" 404 188 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 
```

in `/var/log/apache2/error.log` I didn't any logs 

But I'm able to access other modules example performance 

`http://192.168.0.136/orangehrm/web/index.php/performance/myPerformanceReview`

![image](https://github.com/orangehrm/orangehrm/assets/91748984/2ab7d7c2-13c6-4063-a293-ce2dd8af6b77)

what can be the problem but which I'm not able to access the `/leave` routes

### Relevant log output

```shell
[2024-06-29T13:08:45.101937+00:00] orangehrm.ERROR: No route found for "GET http://192.168.0.136/orangehrm/web/index.php/leave/showLeavePeriodNotDefinedWarning" [] []
[2024-06-29T13:08:45.102194+00:00] orangehrm.ERROR: #0 /var/www/html/orangehrm/src/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest() #1 /var/www/html/orangehrm/src/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #2 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #3 /var/www/html/orangehrm/src/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #4 /var/www/html/orangehrm/src/lib/framework/Framework.php(156): Symfony\Component\HttpKernel\HttpKernel->handle() #5 /var/www/html/orangehrm/web/index.php(41): OrangeHRM\Framework\Framework->handleRequest() #6 {main} [] []
```
```

**Comment by rbale3108** [comment]
I have also given 
```
sudo chmod -R 777 /var/www/html/
sudo chown -R www-data: /var/www/html/

sudo service apache2 restart
sudo service php8.1-fpm restart
```
then too not working 

what can be the problem

**Comment by devishke-orange** [comment]
Hi @rbale3108 

This is a known bug. We will fix it in a later version. For now, please define the leave period using an admin account first before accessing the leave module as an employee.

**Comment by rbale3108** [comment]
Hi @devishke-orange ,

Can you please let me know, by when you will release the next version with fixing this bug.

**Comment by Fathimun** [comment]
please let us know once its fixed..

**Comment by ash-esm** [comment]
Also getting this issue.

**Comment by ash-esm** [comment]
Found the issue, you need to login as an admin and set an initial leave period. Once it exists the page works for users.
