### ISSUE TITLE
Error when attempting to sync with LDAP

### ISSUE THREAD

**Issue by aMMgYrP** [orangehrm/orangehrm#1874]
### OrangeHRM version

5.7

### Environment details

- OrangeHRM source:
- Platform: Ubuntu 24.04
- PHP version: 8.3.6
- Database and version: 10.11.8-MariaDB
- Web server: Apache 2.4.58 
- Browser: N/A

### Describe the bug

When attempting to sync with LDAP, the sync fails with errors written to /var/www/html/orangehrm-5.7/src/log/ldap.log

### To reproduce

Attempt to sync OrangeHRM with Active Directory 

### Expected behavior

AD would sync and users would populate. 

### Relevant log output

```shell
[2024-10-03T17:12:01.743723+00:00] LDAP.ERROR: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb3_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=' [] []
[2024-10-03T17:12:01.743895+00:00] LDAP.ERROR: #0 /var/www/html/orangehrm-5.7/src/vendor/doctrine/dbal/src/Connection.php(1943): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/orangehrm-5.7/src/vendor/doctrine/dbal/src/Connection.php(1885): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/orangehrm-5.7/src/vendor/doctrine/dbal/src/Connection.php(1106): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/orangehrm-5.7/src/vendor/doctrine/orm/src/Query/Exec/SingleSelectExecutor.php(33): Doctrine\DBAL\Connection->executeQuery() #4 /var/www/html/orangehrm-5.7/src/vendor/doctrine/orm/src/Query.php(327): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute() #5 /var/www/html/orangehrm-5.7/src/vendor/doctrine/orm/src/AbstractQuery.php(1212): Doctrine\ORM\Query->_doExecute() #6 /var/www/html/orangehrm-5.7/src/vendor/doctrine/orm/src/AbstractQuery.php(1166): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() #7 /var/www/html/orangehrm-5.7/src/vendor/doctrine/orm/src/AbstractQuery.php(953): Doctrine\ORM\AbstractQuery->execute() #8 /var/www/html/orangehrm-5.7/src/plugins/orangehrmLDAPAuthenticationPlugin/Dao/LDAPDao.php(110): Doctrine\ORM\AbstractQuery->getOneOrNullResult() #9 /var/www/html/orangehrm-5.7/src/plugins/orangehrmLDAPAuthenticationPlugin/Service/LDAPSyncService.php(234): OrangeHRM\LDAP\Dao\LDAPDao->getAuthProviderByUserUniqueId() #10 /var/www/html/orangehrm-5.7/src/plugins/orangehrmLDAPAuthenticationPlugin/Service/LDAPSyncService.php(374): OrangeHRM\LDAP\Service\LDAPSyncService->createSystemUsers() #11 /var/www/html/orangehrm-5.7/src/plugins/orangehrmLDAPAuthenticationPlugin/Api/LDAPUserSyncAPI.php(158): OrangeHRM\LDAP\Service\LDAPSyncService->sync() #12 /var/www/html/orangehrm-5.7/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/GenericRestController.php(112): OrangeHRM\LDAP\Api\LDAPUserSyncAPI->create() #13 /var/www/html/orangehrm-5.7/src/plugins/orangehrmCorePlugin/Controller/Rest/V2/AbstractRestController.php(149): OrangeHRM\Core\Controller\Rest\V2\GenericRestController->handlePostRequest() #14 /var/www/html/orangehrm-5.7/src/vendor/symfony/http-kernel/HttpKernel.php(163): OrangeHRM\Core\Controller\Rest\V2\AbstractRestController->handle() #15 /var/www/html/orangehrm-5.7/src/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #16 /var/www/html/orangehrm-5.7/src/lib/framework/Framework.php(156): Symfony\Component\HttpKernel\HttpKernel->handle() #17 /var/www/html/orangehrm-5.7/web/index.php(41): OrangeHRM\Framework\Framework->handleRequest() #18 {main} [] []
```

**Comment by myndbreaker** [comment]
I had the same Problem and reinstalled with Version 5.2 which added LDAP Support. The error is still the same. 

Oracle Linux 8
PHP 7.4
mariadb 10.3

**Comment by howardshand** [comment]
Possibly related to #1614, interim solution use text or int field as "User Unique ID Attribute".
