### ISSUE TITLE
Stuck on installation (checking database permissions)

### ISSUE THREAD

**Issue by itrrmp** [orangehrm/orangehrm#1880]
### OrangeHRM version

5.7

### Environment details

- Platform: windows
- PHP version: 8.3.9 
- Database and version: mariadb 10.2
- Web server: default
- Browser: chrome

### Describe the bug

The fresh installation from orangehrm setup with docker compose is stuck on "checking database permissions", I tried the orangehrm/latest, and other mariadb versions and it happens the same thing. I already checked all the previously created issues similar to this and none of the suggested solutions worked.

![Captura de ecrã 2024-10-18 174240](https://github.com/user-attachments/assets/1f03d7ea-6d19-4097-aef6-b8728fe47ea9)

### To reproduce

1. Run docker-compose up
2. Open orangehrm at the specified IP
3. Proceed with the installation

### Relevant log output

```shell
installer.log:

[2024-10-18T16:38:43.393336+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away [] []
[2024-10-18T16:38:43.400770+00:00] installer.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1943): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1885): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1213): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1617): Doctrine\DBAL\Connection->executeStatement() #4 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1243): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql() #5 /var/www/html/installer/Util/V1/SchemaHelper.php(198): Doctrine\DBAL\Schema\AbstractSchemaManager->alterTable() #6 /var/www/html/installer/Util/DatabaseUserPermissionEvaluator.php(260): OrangeHRM\Installer\Util\V1\SchemaHelper->addForeignKey() #7 /var/www/html/installer/Util/DatabaseUserPermissionEvaluator.php(363): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalForeignKeyPermission() #8 /var/www/html/installer/Controller/Upgrader/Api/PreMigrationCheck.php(35): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalPrivilegeDatabaseUserPermission() #9 /var/www/html/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\PreMigrationCheck->handlePost() #10 /var/www/html/installer/Controller/AbstractInstallerController.php(84): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(163): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/installer/Framework/HttpKernel.php(243): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #15 {main} [] []
```

**Comment by itrrmp** [comment]
Tested at home with my arm macbook and it worked. Whats going on here? Where can I see some logs?

**Comment by itrrmp** [comment]
installer.log:

[2024-10-21T11:03:08.854976+00:00] installer.INFO: Matched route "{route}". {"route":"installer_home","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\HomeController::handle","_route":"installer_home"},"request_uri":"http://127.0.0.1:8082/installer/index.php/","method":"GET"} []
[2024-10-21T11:03:08.869160+00:00] installer.INFO: Matched route "{route}". {"route":"installer_welcome","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\WelcomeController::handle","_route":"installer_welcome"},"request_uri":"http://127.0.0.1:8082/installer/index.php/welcome","method":"GET"} []
[2024-10-21T11:03:11.420625+00:00] installer.INFO: Matched route "{route}". {"route":"installer_licence_acceptance","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\LicenceAcceptanceController::handle","_route":"installer_licence_acceptance"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/licence-acceptance","method":"GET"} []
[2024-10-21T11:03:13.902943+00:00] installer.INFO: Matched route "{route}". {"route":"installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\DatabaseConfigController::handle","_route":"installer_database_config"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/database-config","method":"GET"} []
[2024-10-21T11:03:13.956850+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/database-config","method":"GET"} []
[2024-10-21T11:03:46.819407+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/database-config","method":"POST"} []
[2024-10-21T11:03:46.836003+00:00] installer.INFO: Instance details: {"os":{"os":"Linux","release_name":"5.15.153.1-microsoft-standard-WSL2","version_info":"#1 SMP Fri Mar 29 23:14:13 UTC 2024"},"php":{"version":"8.3.9"},"mysql":{"client_version":"mysqlnd 8.3.9","server_version":"10.2.44-MariaDB-1:10.2.44+maria~bionic","conn_type":"orangehrm-mariadb-1 via TCP\/IP"},"server":"Apache\/2.4.59 (Debian)","ohrm":{"version":"5.7"}} [] []
[2024-10-21T11:03:46.880412+00:00] installer.INFO: Matched route "{route}". {"route":"installer_system_check","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\SystemCheckController::handle","_route":"installer_system_check"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/system-check","method":"GET"} []
[2024-10-21T11:03:46.927248+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_system_check","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\SystemCheckAPI::handle","_route":"api_installer_system_check"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/system-check","method":"GET"} []
[2024-10-21T11:03:52.899517+00:00] installer.INFO: Matched route "{route}". {"route":"installer_instance_creation","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\InstanceCreationController::handle","_route":"installer_instance_creation"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/instance-creation","method":"GET"} []
[2024-10-21T11:03:52.946052+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_countries","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\CountryAPI::handle","_route":"api_installer_countries"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/countries","method":"GET"} []
[2024-10-21T11:03:52.964574+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_languages","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\LanguageAPI::handle","_route":"api_installer_languages"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/languages","method":"GET"} []
[2024-10-21T11:03:52.977699+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_timezones","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\TimezoneAPI::handle","_route":"api_installer_timezones"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/timezones","method":"GET"} []
[2024-10-21T11:03:53.005429+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_instance","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\InstanceAPI::handle","_route":"api_installer_instance"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/instance","method":"GET"} []
[2024-10-21T11:04:19.044746+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_instance","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\InstanceAPI::handle","_route":"api_installer_instance"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/instance","method":"POST"} []
[2024-10-21T11:04:19.067389+00:00] installer.INFO: Matched route "{route}". {"route":"installer_admin_user_creation","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\AdminUserCreationController::handle","_route":"installer_admin_user_creation"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/admin-user-creation","method":"GET"} []
[2024-10-21T11:04:19.124902+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_admin_user","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\AdminUserAPI::handle","_route":"api_installer_admin_user"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/admin-user","method":"GET"} []
[2024-10-21T11:04:59.825007+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_admin_user","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\AdminUserAPI::handle","_route":"api_installer_admin_user"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/admin-user","method":"POST"} []
[2024-10-21T11:04:59.846579+00:00] installer.INFO: Matched route "{route}". {"route":"installer_confirmation","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\ConfirmationController::handle","_route":"installer_confirmation"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/confirmation","method":"GET"} []
[2024-10-21T11:04:59.902871+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database_config","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\DatabaseConfigAPI::handle","_route":"api_installer_database_config"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/database-config","method":"GET"} []
[2024-10-21T11:04:59.917823+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_admin_user","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\AdminUserAPI::handle","_route":"api_installer_admin_user"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/admin-user","method":"GET"} []
[2024-10-21T11:05:03.267252+00:00] installer.INFO: Matched route "{route}". {"route":"installer_process","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\InstallerController::handle","_route":"installer_process"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/process","method":"GET"} []
[2024-10-21T11:05:03.315607+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_start_registration","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\InstallerDataRegistrationAPI::handle","_route":"api_installer_start_registration"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/send-data/installer-start","method":"POST"} []
[2024-10-21T11:05:03.317429+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_database","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\InstallationDatabaseAPI::handle","_route":"api_installer_database"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/installation/database","method":"POST"} []
[2024-10-21T11:05:03.320894+00:00] installer.INFO: Instance details: {"os":{"os":"Linux","release_name":"5.15.153.1-microsoft-standard-WSL2","version_info":"#1 SMP Fri Mar 29 23:14:13 UTC 2024"},"php":{"version":"8.3.9"},"mysql":{"client_version":"mysqlnd 8.3.9","server_version":"10.2.44-MariaDB-1:10.2.44+maria~bionic","conn_type":"orangehrm-mariadb-1 via TCP\/IP"},"server":"Apache\/2.4.59 (Debian)","ohrm":{"version":"5.7"}} [] []
[2024-10-21T11:05:03.355646+00:00] installer.INFO: Matched route "{route}". {"route":"api_installer_pre_migration_check","route_parameters":{"_controller":"OrangeHRM\\Installer\\Controller\\Installer\\Api\\PreMigrationCheck::handle","_route":"api_installer_pre_migration_check"},"request_uri":"http://127.0.0.1:8082/installer/index.php/installer/api/installation/pre-migration","method":"POST"} []
[2024-10-21T11:05:03.359377+00:00] installer.INFO: Instance details: {"os":{"os":"Linux","release_name":"5.15.153.1-microsoft-standard-WSL2","version_info":"#1 SMP Fri Mar 29 23:14:13 UTC 2024"},"php":{"version":"8.3.9"},"mysql":{"client_version":"mysqlnd 8.3.9","server_version":"10.2.44-MariaDB-1:10.2.44+maria~bionic","conn_type":"orangehrm-mariadb-1 via TCP\/IP"},"server":"Apache\/2.4.59 (Debian)","ohrm":{"version":"5.7"}} [] []
[2024-10-21T11:05:20.860761+00:00] installer.ERROR: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away [] []
[2024-10-21T11:05:20.860822+00:00] installer.ERROR: #0 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1943): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() #1 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1885): Doctrine\DBAL\Connection->handleDriverException() #2 /var/www/html/src/vendor/doctrine/dbal/src/Connection.php(1213): Doctrine\DBAL\Connection->convertExceptionDuringQuery() #3 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1617): Doctrine\DBAL\Connection->executeStatement() #4 /var/www/html/src/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(1243): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql() #5 /var/www/html/installer/Util/V1/SchemaHelper.php(198): Doctrine\DBAL\Schema\AbstractSchemaManager->alterTable() #6 /var/www/html/installer/Util/DatabaseUserPermissionEvaluator.php(260): OrangeHRM\Installer\Util\V1\SchemaHelper->addForeignKey() #7 /var/www/html/installer/Util/DatabaseUserPermissionEvaluator.php(363): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalForeignKeyPermission() #8 /var/www/html/installer/Controller/Upgrader/Api/PreMigrationCheck.php(35): OrangeHRM\Installer\Util\DatabaseUserPermissionEvaluator->evalPrivilegeDatabaseUserPermission() #9 /var/www/html/installer/Controller/AbstractInstallerRestController.php(57): OrangeHRM\Installer\Controller\Upgrader\Api\PreMigrationCheck->handlePost() #10 /var/www/html/installer/Controller/AbstractInstallerController.php(84): OrangeHRM\Installer\Controller\AbstractInstallerRestController->execute() #11 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(163): OrangeHRM\Installer\Controller\AbstractInstallerController->handle() #12 /var/www/html/src/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw() #13 /var/www/html/installer/Framework/HttpKernel.php(243): Symfony\Component\HttpKernel\HttpKernel->handle() #14 /var/www/html/installer/index.php(65): OrangeHRM\Installer\Framework\HttpKernel->handleRequest() #15 {main} [] []

**Comment by itrrmp** [comment]
Mariadb docker container logs:

`2024-10-21 13:29:40+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.2.44+maria~bionic started.
2024-10-21 13:29:40+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-10-21 13:29:40+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.2.44+maria~bionic started.
2024-10-21 13:29:40+00:00 [Note] [Entrypoint]: Initializing database files


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:

'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at http://mariadb.com/kb

Please report any problems at http://mariadb.org/jira

The latest information about MariaDB is available at http://mariadb.org/.

Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2024-10-21 13:29:48+00:00 [Note] [Entrypoint]: Database files initialized
2024-10-21 13:29:48+00:00 [Note] [Entrypoint]: Starting temporary server
2024-10-21 13:29:48+00:00 [Note] [Entrypoint]: Waiting for server startup
2024-10-21 13:29:48 139840393397952 [Note] mysqld (mysqld 10.2.44-MariaDB-1:10.2.44+maria~bionic) starting as process 116 ...
2024-10-21 13:29:48 139840393397952 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Uses event mutexes
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Compressed tables use zlib 1.2.11
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Using Linux native AIO
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Number of pools: 1
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Using SSE2 crc32 instructions
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Completed initialization of buffer pool
2024-10-21 13:29:48 139839666337536 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2024-10-21 13:29:48 139840393397952 [Note] InnoDB: Highest supported file format is Barracuda.
2024-10-21 13:29:49 139840393397952 [Note] InnoDB: 128 out of 128 rollback segments are active.
2024-10-21 13:29:49 139840393397952 [Note] InnoDB: Creating shared tablespace for temporary tables
2024-10-21 13:29:49 139840393397952 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2024-10-21 13:29:49 139840393397952 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2024-10-21 13:29:49 139840393397952 [Note] InnoDB: Waiting for purge to start
2024-10-21 13:29:49 139840393397952 [Note] InnoDB: 5.7.38 started; log sequence number 1615498
2024-10-21 13:29:49 139840393397952 [Note] Plugin 'FEEDBACK' is disabled.
2024-10-21 13:29:49 139840393397952 [Warning] 'user' entry 'root@7705b1835ab0' ignored in --skip-name-resolve mode.
2024-10-21 13:29:49 139840393397952 [Warning] 'proxies_priv' entry '@% root@7705b1835ab0' ignored in --skip-name-resolve mode.
2024-10-21 13:29:49 139840393397952 [Note] Reading of all Master_info entries succeeded
2024-10-21 13:29:49 139840393397952 [Note] Added new Master_info '' to hash table
2024-10-21 13:29:49 139840393397952 [Note] mysqld: ready for connections.
Version: '10.2.44-MariaDB-1:10.2.44+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2024-10-21 13:29:49+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
2024-10-21 13:30:10+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
2024-10-21 13:30:10+00:00 [Note] [Entrypoint]: Creating database orangehrm

2024-10-21 13:30:10+00:00 [Note] [Entrypoint]: Stopping temporary server
2024-10-21 13:30:10 139840246359808 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2024-10-21 13:30:10 139840246359808 [Note] Event Scheduler: Purging the queue. 0 events
2024-10-21 13:30:10 139839546574592 [Note] InnoDB: FTS optimize thread exiting.
2024-10-21 13:30:10 139840246359808 [Note] InnoDB: Starting shutdown...
2024-10-21 13:30:10 139839227815680 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2024-10-21 13:30:10 139839227815680 [Note] InnoDB: Buffer pool(s) dump completed at 241021 13:30:10
2024-10-21 13:30:12 139840246359808 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2024-10-21 13:30:12 139840246359808 [Note] InnoDB: Shutdown completed; log sequence number 1615526
2024-10-21 13:30:12 139840246359808 [Note] mysqld: Shutdown complete

2024-10-21 13:30:12+00:00 [Note] [Entrypoint]: Temporary server stopped

2024-10-21 13:30:12+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.

2024-10-21 13:30:12 140125846767296 [Note] mysqld (mysqld 10.2.44-MariaDB-1:10.2.44+maria~bionic) starting as process 1 ...
2024-10-21 13:30:12 140125846767296 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Uses event mutexes
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Compressed tables use zlib 1.2.11
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Using Linux native AIO
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Number of pools: 1
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Using SSE2 crc32 instructions
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Completed initialization of buffer pool
2024-10-21 13:30:12 140125117658880 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Highest supported file format is Barracuda.
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: 128 out of 128 rollback segments are active.
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Creating shared tablespace for temporary tables
2024-10-21 13:30:12 140125846767296 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2024-10-21 13:30:13 140125846767296 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2024-10-21 13:30:13 140125846767296 [Note] InnoDB: 5.7.38 started; log sequence number 1615526
2024-10-21 13:30:13 140124817962752 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-10-21 13:30:13 140125846767296 [Note] Plugin 'FEEDBACK' is disabled.
2024-10-21 13:30:13 140124817962752 [Note] InnoDB: Buffer pool(s) load completed at 241021 13:30:13
2024-10-21 13:30:13 140125846767296 [Note] Server socket created on IP: '::'.
2024-10-21 13:30:13 140125846767296 [Note] Reading of all Master_info entries succeeded
2024-10-21 13:30:13 140125846767296 [Note] Added new Master_info '' to hash table
2024-10-21 13:30:13 140125846767296 [Note] mysqld: ready for connections.
Version: '10.2.44-MariaDB-1:10.2.44+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2024-10-21 13:32:09 140125480662784 [ERROR] InnoDB: preallocating 131072 bytes for file ./orangehrm/_ohrm_temp_table.ibd failed with error 2
2024-10-21 13:32:09 0x7f71817fb700  InnoDB: Assertion failure in file /home/buildbot/buildbot/build/mariadb-10.2.44/storage/innobase/fil/fil0fil.cc line 1006       
InnoDB: Failing assertion: fsize != os_offset_t(-1)
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to https://jira.mariadb.org/
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: https://mariadb.com/kb/en/library/innodb-recovery-modes/
InnoDB: about forcing recovery.
241021 13:32:09 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 10.2.44-MariaDB-1:10.2.44+maria~bionic
key_buffer_size=134217728
read_buffer_size=2097152
max_used_connections=2
max_threads=102
thread_count=7
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 759916 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7f7118000c08
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x7f71817fadd8 thread_stack 0x49000
mysqld(my_print_stacktrace+0x2e)[0x560f961f3cfe]
mysqld(handle_fatal_signal+0x513)[0x560f95c8f5f3]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f7195a32980]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f7194f46e87]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f7194f487f1]
mysqld(+0x432710)[0x560f95a32710]
mysqld(+0x434ae9)[0x560f95a34ae9]
mysqld(+0xa1a34f)[0x560f9601a34f]
mysqld(+0x434dbd)[0x560f95a34dbd]
mysqld(+0xa2fa07)[0x560f9602fa07]
mysqld(+0xa3363b)[0x560f9603363b]
mysqld(+0x96fb04)[0x560f95f6fb04]
mysqld(+0x9dd4ac)[0x560f95fdd4ac]
mysqld(+0x9ddb7d)[0x560f95fddb7d]
mysqld(+0x8a2382)[0x560f95ea2382]
mysqld(+0x8c9b59)[0x560f95ec9b59]
mysqld(+0x42c834)[0x560f95a2c834]
mysqld(+0x8286e7)[0x560f95e286e7]
mysqld(+0x425e49)[0x560f95a25e49]
mysqld(_Z17mysql_alter_tableP3THDPcS1_P14HA_CREATE_INFOP10TABLE_LISTP10Alter_infojP8st_orderb+0x3972)[0x560f95b7bb62]
mysqld(_ZN19Sql_cmd_alter_table7executeEP3THD+0x3de)[0x560f95bc831e]
mysqld(_Z21mysql_execute_commandP3THD+0x231f)[0x560f95aef54f]
mysqld(_Z11mysql_parseP3THDPcjP12Parser_statebb+0x2be)[0x560f95af502e]
mysqld(_Z16dispatch_command19enum_server_commandP3THDPcjbb+0x190d)[0x560f95af759d]
mysqld(_Z10do_commandP3THD+0x12b)[0x560f95af86cb]
mysqld(_Z24do_handle_one_connectionP7CONNECT+0x32e)[0x560f95bc568e]
mysqld(handle_one_connection+0x3d)[0x560f95bc575d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f7195a276db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f719502961f]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x7f711800f240): ALTER TABLE _ohrm_temp_table ADD CONSTRAINT fk_id FOREIGN KEY (foreign_id) REFERENCES _ohrm_temp_foreign_table (id) ON UPDATE NO ACTION ON DELETE SET NULL

Connection ID (thread ID): 27
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=off,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on

The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mysqld/ contains
information that should help you find out what is causing the crash.
Writing a core file...
Working directory at /var/lib/mysql
Resource Limits:
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             unlimited            unlimited            processes
Max open files            1048576              1048576              files
Max locked memory         unlimited            unlimited            bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       31014                31014                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
Core pattern: |/wsl-capture-crash %t %E %p %s

Fatal signal 11 while backtracing`

**Comment by itrrmp** [comment]
Well, I disabled WSL2 in docker desktop settings and it solved the problem.
[](https://stackoverflow.com/questions/70784437/innodb-preallocating-147456-bytes-for-file-xxx-ibd-failed-with-error-2)

**Comment by anikwai** [comment]
Run into the same issue,took for ever to pass this step.

![Image](https://github.com/user-attachments/assets/96846221-5f68-43ca-bb00-158300012387)

- Ubuntu Server 22.04
- PHP 8.1
- Mariadb 10.4
- Apache Webserver
- Chrome
