### ISSUE TITLE
Home page does NOT show login button

### ISSUE THREAD

**Issue by srigurubyo** [orangehrm/orangehrm#417]
Hi, I just downloaded 4.2 (the latest version from sourceforge.net) and tried installing it in DigitalOcean LAMP server.  

I could bring the OrangeHRM up but my initial installation process is stuck at step 1 and not moving further (Clicking **Next** button just refreshes the same page and doesn't do any work).

Thanks in advance for any help here!
![screenshot from 2018-10-31 23-26-28](https://user-images.githubusercontent.com/10773464/47808516-8acda080-dd64-11e8-859e-a08f430200b3.png)

My environment is:

- Ubuntu 18.04
- PHP 7.0.32

**Comment by srigurubyo** [comment]
It did not work even after multiple restarts and different tries.  

However, I was exploring the 'upgrading' option and came back to home page of installer.  It worked finally.

Not sure what was going on there.

**Comment by srigurubyo** [comment]
Now, after successful installation, I don't see **LOGIN** button on the home page.  I am really clueless what is happening.

![screenshot from 2018-11-01 08-06-18](https://user-images.githubusercontent.com/10773464/47829445-90030d80-ddad-11e8-9ee5-29e4f65aec8f.png)

**Comment by srigurubyo** [comment]
I tried in different browsers, same result.

**Comment by srigurubyo** [comment]
Here is the error in the log file.

`[01-Nov-2018 08:01:17 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:01:38 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:05:20 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:05:24 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:05:57 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:06:04 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:12:34 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:12:46 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
[01-Nov-2018 08:13:11 Asia/Kolkata] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php:54
Stack trace:
#0 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_Aggregate.class.php(99): sfMessageSource_XLIFF->loadData('/var/www/html/o...')
#1 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource.class.php(198): sfMessageSource_Aggregate->loadData(Array)
#2 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(139): sfMessageSource->load('messages')
#3 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(193): sfMessageFormat->loadCatalogue('messages')
#4 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageFormat.class.php(168): sfMessageFormat->formatString('LOGIN Panel', Array, 'messages')
#5 /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfI18N.class.php(230): sfMessageFormat->format('L in /var/www/html/orangehrm42/symfony/lib/vendor/symfony/lib/i18n/sfMessageSource_XLIFF.class.php on line 54
`

**Comment by srigurubyo** [comment]
Installed php7.0-xml and the error is gone now.
