### ISSUE TITLE
4.3.1 System Chec  blanck page in ubuntu 

### ISSUE THREAD

**Issue by rimer10** [orangehrm/orangehrm#514]
php : PHP 7.2.17-0ubuntu0.19.04.1 (cli)
mysql : mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

i try but in the 4th step its show blank page 

somebody please tell me how can i fix this? 

permission `chown -R www-data:www-data/folder`

![hrm](https://user-images.githubusercontent.com/36982239/57845878-8cd2ea80-77f0-11e9-90f2-9dc5bc15355f.png)

**Comment by rimer10** [comment]
here is my error log 

`PHP Warning:  require(/var/www/html/orangehrm-4.3.1/installer/environmentCheck/../../symfony/lib/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/orangehrm-4.3.1/installer/environmentCheck/SystemValidator.php on line 22`
`
` PHP Fatal error:  require(): Failed opening required '/var/www/html/orangehrm-4.3.1/installer/environmentCheck/../../symfony/lib/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/orangehrm-4.3.1/installer/environmentCheck/SystemValidator.php on line 22``

**Comment by RajithaKumara** [comment]
Hi @rimer10 
If you get the source from this repo please refer #440 and #437.

**Comment by rimer10** [comment]
@RajithaKumara  thank you but still i have a problem 

`PHP Version should be higher than 5.6 and lower than 7.2.5 .Installed version is 7.2.17-0ubuntu0.19.04.1`

`MySql Version should be higher than 5.5 and lower than 5.7.23 .Installed version is 5.7.26-0ubuntu0.19.04.1`

is that any possible way to install this with out downgrade php and mysql?

**Comment by RajithaKumara** [comment]
Sure. Please refer #490 and #360. But we can't recommend for production.

**Comment by rimer10** [comment]
@RajithaKumara thz for this fast replay ill check and i close my self as this issue thank you again

**Comment by rimer10** [comment]
i try but installl.php error here is my error log

```
[17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  mysqli_connect(): (HY000/2002): No such file or directory in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 97
[17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 70
[17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  mysqli_errno() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 73
[17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 75
[17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 86
[17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  include_once(../symfony/plugins/orangehrmCorePlugin/lib/utility/PasswordHash.php): failed to open stream: No such file or directory in /var/www/html/rhrma/installer/SystemConfiguration.php on line 21
[17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  include_once(): Failed opening '../symfony/plugins/orangehrmCorePlugin/lib/utility/PasswordHash.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/rhrma/installer/SystemConfiguration.php on line 21
[17-May-2019 21:33:11 Asia/Kolkata] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'orangehrm_mysql' in /var/www/html/rhrma/installer/SystemConfiguration.php:39
Stack trace:
#0 /var/www/html/rhrma/installer/SystemConfiguration.php(39): PDO->__construct('mysql:host=loca...', 'root', 'password')
#1 /var/www/html/rhrma/installer/SystemConfiguration.php(55): SystemConfiguration->createDbConnection()
#2 /var/www/html/rhrma/installer/applicationSetup.php(30): SystemConfiguration->setOrganizationName('test')
#3 /var/www/html/rhrma/install.php(275): include('/var/www/html/r...')
#4 {main}
  thrown in /var/www/html/rhrma/installer/SystemConfiguration.php on line 39
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  mysqli_connect(): (HY000/2002): No such file or directory in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 97
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  mysqli_select_db() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 134
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 135
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  mysqli_connect(): (HY000/2002): No such file or directory in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 97
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 533
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, boolean given in /var/www/html/rhrma/installer/ApplicationSetupUtility.php on line 534
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  include_once(../symfony/plugins/orangehrmCorePlugin/lib/utility/PasswordHash.php): failed to open stream: No such file or directory in /var/www/html/rhrma/installer/SystemConfiguration.php on line 21
[17-May-2019 21:33:20 Asia/Kolkata] PHP Warning:  include_once(): Failed opening '../symfony/plugins/orangehrmCorePlugin/lib/utility/PasswordHash.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/rhrma/installer/SystemConfiguration.php on line 21
[17-May-2019 21:33:20 Asia/Kolkata] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'orangehrm_mysql' in /var/www/html/rhrma/installer/SystemConfiguration.php:39
Stack trace:
#0 /var/www/html/rhrma/installer/SystemConfiguration.php(39): PDO->__construct('mysql:host=loca...', 'root', 'password')
#1 /var/www/html/rhrma/installer/SystemConfiguration.php(55): SystemConfiguration->createDbConnection()
#2 /var/www/html/rhrma/installer/applicationSetup.php(30): SystemConfiguration->setOrganizationName('test')
#3 /var/www/html/rhrma/install.php(275): include('/var/www/html/r...')
#4 {main}
  thrown in /var/www/html/rhrma/installer/SystemConfiguration.php on line 39
```

**Comment by RajithaKumara** [comment]
Is this stack trace came from Orangehrm 4.3.1 branch? Because I'm bit confused with stack trace line numbers. Could you please update working branch from `orangehrm/orangehrm`. If you did changes to the source code, please run `git stash` before pull.
Also,
> [17-May-2019 21:33:11 Asia/Kolkata] PHP Warning:  include_once(../symfony/plugins/orangehrmCorePlugin/lib/utility/PasswordHash.php): failed to open stream: No such file or directory in /var/www/html/rhrma/installer/SystemConfiguration.php on line 21

this cannot be happen.

**Comment by kavithagurusamy** [comment]
@rimer10 
Can you please let me know the status of the issue?

I need to close it if it is resolved else we need to identify the issue to fix in our next release.

**Comment by rimer10** [comment]
sorry i forget same issue wait ill post my logs here thank you @kavithagurusamy @RajithaKumara

**Comment by shadowboo** [comment]
@RajithaKumara  thank you i'm also face same  issue but #490  and #360  solve my problem
