### ISSUE TITLE
Unable to upload photo with 500 error

### ISSUE THREAD

**Issue by saviour123** [orangehrm/orangehrm#530]
My installation works fine except for employee photo upload. When I try to upload a photo, the web server throws the following error. I checked my logs and no apparent clue is there

System:
PHP 7.1.30-1
Ubuntu 18.04/nginx webserver
Orange: 4.3.1

```
Stack trace:
#0 /var/www/orangehrm/symfony/lib/vendor/symfony/lib/filter/sfBasicSecurityFilter.class.php(55): sfBasicSecurityFilter->forwardToLoginAction()
#1 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1048): sfBasicSecurityFilter->execute(Object(sfFilterChain))
#2 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1013): sfFilterChain->execute()
#3 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1048): sfRenderingFilter->execute(Object(sfFilterChain))
#4 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(687): sfFilterChain->execute()
#5 /var/www/orangehrm/symfony/lib/vendor/symfony/lib/exception/sfError404Exception.class.php(49): sfController->forward('default', 'error404')
#6 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.ym in /var/www/orangehrm/symfony/lib/vendor/symfony/lib/filter/sfBasicSecurityFilter.class.php on line 96
[17-Jun-2019 11:23:05 UTC] Empty module and/or action after parsing the URL "/favicon.ico" (/).
[17-Jun-2019 12:34:59 UTC] Empty module and/or action after parsing the URL "/favicon.ico" (/).
[17-Jun-2019 12:34:59 UTC] PHP Fatal error:  Uncaught sfStopException in /var/www/orangehrm/symfony/lib/vendor/symfony/lib/filter/sfBasicSecurityFilter.class.php:96
Stack trace:
#0 /var/www/orangehrm/symfony/lib/vendor/symfony/lib/filter/sfBasicSecurityFilter.class.php(55): sfBasicSecurityFilter->forwardToLoginAction()
#1 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1048): sfBasicSecurityFilter->execute(Object(sfFilterChain))
#2 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1013): sfFilterChain->execute()
#3 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1048): sfRenderingFilter->execute(Object(sfFilterChain))
#4 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(687): sfFilterChain->execute()
#5 /var/www/orangehrm/symfony/lib/vendor/symfony/lib/exception/sfError404Exception.class.php(49): sfController->forward('default', 'error404')
#6 /var/www/orangehrm/symfony/cache/orangehrm/prod/config/config_core_compile.ym in /var/www/orangehrm/symfony/lib/vendor/symfony/lib/filter/sfBasicSecurityFilter.class.php on line 96
```

**Comment by RajithaKumara** [comment]
Hi @saviour123 
What is the OrangeHRM version and PHP version which you are using?

**Comment by saviour123** [comment]
Updated.

**Comment by RajithaKumara** [comment]
Did you mean employee photograph as **photo upload**?

**Comment by saviour123** [comment]
Yes

**Comment by RajithaKumara** [comment]
It work for me with [OrangeHRM](https://sourceforge.net/projects/orangehrm/):4.3.1 in (Docker environment)
PHP:7.1.30
Nginx:1.13

Could you please try with different extensions. (eg: .jpg, .png)
Also try clearing `symfony` cache by executing
```bash
$ cd path_to_symfony_dir
$ php symfony cc
```

**Comment by kavithagurusamy** [comment]
Can I close this ticket since @saviour123 was able to upload the photo

**Comment by saviour123** [comment]
This is due to a proxy permission issue, nginx is not able to create temp file /var/lib/nginx, after changing the user and owner of the file path to www-data, everything works fine.
