### ISSUE TITLE
Marketplace - Error Occur Please try again later

### ISSUE THREAD

**Issue by 22phuber** [orangehrm/orangehrm#569]
After a fresh installation of OrangeHRM (without registration in installation wizard), the marketplace is not working.

![OrangeHRM_MarketplaceError](https://user-images.githubusercontent.com/17426101/65371581-5e18c500-dc65-11e9-85c3-c97d20615b1b.gif)

```
==> /var/www/orangehrm_stoneageit/symfony/log/orangehrm.log <==
Sat 21 Sep 2019 11:16:32 AM CEST,952 [21683] ERROR orangehrm - 500 : Server error: `POST https://marketplace.orangehrm.com/api/v1/handshake` resulted in a `500 Internal Server Error` response:
{"error":{"code":500,"message":"Internal Server Error"}}

Sat 21 Sep 2019 11:16:32 AM CEST,952 [21683] ERROR orangehrm - #0 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/orangehrm_stoneageit/symfony/lib/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('post', '/api/v1/handsha...', Array)
#11 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmMarketPlacePlugin/lib/manager/APIManagerService.php(391): GuzzleHttp\Client->__call('post', Array)
#12 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmMarketPlacePlugin/lib/manager/APIManagerService.php(149): APIManagerService->handShakeWithMarketPlace()
#13 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmMarketPlacePlugin/lib/manager/APIManagerService.php(74): APIManagerService->getApiToken()
#14 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmMarketPlacePlugin/lib/manager/APIManagerService.php(63): APIManagerService->getAddonsFromMP(true)
#15 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmMarketPlacePlugin/modules/marketPlace/actions/baseAddonAction.class.php(84): APIManagerService->getAddons(true)
#16 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmMarketPlacePlugin/modules/marketPlace/actions/ohrmAddonsAction.class.php(86): baseAddonAction->getAddons(true)
#17 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(967): ohrmAddonsAction->execute(Object(sfWebRequest))
#18 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmCorePlugin/lib/filter/orangehrmExecutionFilter.php(42): sfExecutionFilter->executeAction(Object(ohrmAddonsAction))
#19 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(962): orangehrmExecutionFilter->executeAction(Object(ohrmAddonsAction))
#20 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(ohrmAddonsAction))
#21 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#22 /var/www/orangehrm_stoneageit/symfony/lib/vendor/symfony/lib/filter/sfCommonFilter.class.php(29): sfFilterChain->execute()
#23 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfCommonFilter->execute(Object(sfFilterChain))
#24 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmCorePlugin/lib/filter/orangehrmPostExecutionFilter.php(22): sfFilterChain->execute()
#25 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): orangehrmPostExecutionFilter->execute(Object(sfFilterChain))
#26 /var/www/orangehrm_stoneageit/symfony/apps/orangehrm/lib/filter/ModuleFilter.php(56): sfFilterChain->execute()
#27 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): ModuleFilter->execute(Object(sfFilterChain))
#28 /var/www/orangehrm_stoneageit/symfony/plugins/orangehrmCorePlugin/lib/authorization/filter/ohrmAuthorizationFilter.php(101): sfFilterChain->execute()
#29 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): ohrmAuthorizationFilter->execute(Object(sfFilterChain))
#30 /var/www/orangehrm_stoneageit/symfony/apps/orangehrm/lib/filter/SessionInfoFetcherFilter.php(67): sfFilterChain->execute()
#31 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): SessionInfoFetcherFilter->execute(Object(sfFilterChain))
#32 /var/www/orangehrm_stoneageit/symfony/apps/orangehrm/lib/filter/OrangeI18NFilter.php(58): sfFilterChain->execute()
#33 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): OrangeI18NFilter->execute(Object(sfFilterChain))
#34 /var/www/orangehrm_stoneageit/symfony/apps/orangehrm/lib/filter/ExceptionCatcherFilter.php(26): sfFilterChain->execute()
#35 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): ExceptionCatcherFilter->execute(Object(sfFilterChain))
#36 /var/www/orangehrm_stoneageit/symfony/lib/vendor/symfony/lib/filter/sfBasicSecurityFilter.class.php(72): sfFilterChain->execute()
#37 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfBasicSecurityFilter->execute(Object(sfFilterChain))
#38 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1009): sfFilterChain->execute()
#39 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#40 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(685): sfFilterChain->execute()
#41 /var/www/orangehrm_stoneageit/symfony/cache/orangehrm/prod/config/config_core_compile.yml.php(2773): sfController->forward('marketPlace', 'ohrmAddons')
#42 /var/www/orangehrm_stoneageit/symfony/lib/vendor/symfony/lib/util/sfContext.class.php(179): sfFrontWebController->dispatch()
#43 /var/www/orangehrm_stoneageit/symfony/web/index.php(22): sfContext->dispatch()
#44 {main}
```

Version OHRM 4.3.3
PHP: ```php -v
PHP 7.2.22-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.22-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies```

- How can i fix this?
- Do i need to register for the marketplace to work?

**Comment by RajithaKumara** [comment]
Hi @22phuber 
Could you please try reinstalling OrangeHRM and register while installation steps.

**Comment by kavithagurusamy** [comment]
@22phuber 
Were you able to get the marketplace working in your instance? Please do let us know if you require any support.

**Comment by 22phuber** [comment]
@kavithagurusamy @RajithaKumara Hi there, thx for the answers. I try to reinstall this weekend and get back to you.

**Comment by 22phuber** [comment]
I re-installed OHRM and the Marketplace is now working. 👍 
I used a curl install script which had some form data missing.
