### ISSUE TITLE
Error updgrading from 3.1.1 to 4.3.4

### ISSUE THREAD

**Issue by AbdulazizFayez** [orangehrm/orangehrm#595]
Good day, 

I got 2 issues.

1. I was upgrading current site (v3.1.1) to latest (as in master - 4.3.4), upon starting the upgrade, all went well until i reached "Database changes" to **start**, it said ```error occurred``` without showing any text.. upon inspecting, it was a json error, not sure what kind of error it was.

![image](https://user-images.githubusercontent.com/16557490/71401986-864e0080-2666-11ea-94e7-f96f0689be89.png)

2. Upon checking with other issues, i checked at ```<orangehrm/upgrader/logs/error.log> ``` and i got the following errors:

```

2019-Dec-24 08:08:56 : MySQL Error: Table 'xm_hr_symfony.ohrm_marketplace_addon' doesn't exist. 
Query: select * from ohrm_marketplace_addon where plugin_name is not null


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(386): UpgradeUtility->executeSql('select * from o...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\executePluginCheckAction.class.php(30): UpgradeUtility->getInstalledAddons()
#3 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): executePluginCheckAction->execute(Object(sfWebRequest))
#4 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(executePluginCheckAction))
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(executePluginCheckAction))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#8 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'executePluginCh...')
#13 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#14 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#15 {main}
2019-Dec-24 08:09:57 : MySQL Error: Table 'xm_hr_symfony.ohrm_marketplace_addon' doesn't exist. 
Query: select * from ohrm_marketplace_addon where plugin_name is not null


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(386): UpgradeUtility->executeSql('select * from o...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(54): UpgradeUtility->getInstalledAddons()
#3 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(15): dbChangeControlAction->getInstalledPlugins()
#4 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#7 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#8 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#9 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#13 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#14 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#15 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#16 {main}
2019-Dec-24 08:09:57 : MySQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'É¬?\?')' at line 1. 
Query: INSERT INTO `hs_hr_config` ( `key`, `value`) VALUES ('csrf_secret', 'Þºíð‹ñ“M]5\]$Y·{+·ÏüìwÄ1¾¨sÏyºKÝgª¬oL)B!;'É¬Ÿ\Ð');


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask59.php(36): UpgradeUtility->executeSql('INSERT INTO `hs...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(30): SchemaIncrementTask59->execute()
#3 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#4 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#8 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#13 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#14 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#15 {main}
2019-Dec-24 08:12:01 : MySQL Error: Table 'xm_hr_symfony.ohrm_marketplace_addon' doesn't exist. 
Query: select * from ohrm_marketplace_addon where plugin_name is not null


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(386): UpgradeUtility->executeSql('select * from o...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(54): UpgradeUtility->getInstalledAddons()
#3 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(15): dbChangeControlAction->getInstalledPlugins()
#4 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#7 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#8 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#9 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#13 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#14 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#15 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#16 {main}
2019-Dec-24 08:12:01 : MySQL Error: Duplicate entry '59' for key 'PRIMARY'. 
Query: INSERT INTO ohrm_upgrade_status
                            (id, status) 
                            VALUES('59' , 'started');


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask.php(63): UpgradeUtility->executeSql('INSERT INTO ohr...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask.php(23): SchemaIncrementTask->createOhrmUpgradeStatus(59)
#3 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask59.php(31): SchemaIncrementTask->execute()
#4 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(30): SchemaIncrementTask59->execute()
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#7 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#8 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#9 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#13 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#14 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#15 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#16 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#17 {main}
2019-Dec-24 08:12:01 : MySQL Error: Incorrect string value: '\xBCG<\x09\xA6X...' for column 'value' at row 1. 
Query: INSERT INTO `hs_hr_config` ( `key`, `value`) VALUES ('csrf_secret', '¼G<	¦X×K¸¿Ò°En"»¸š€²˜OÎÐ¦e
Nê5à8·â/îéyf+²Piß¼b¡–×)');


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask59.php(36): UpgradeUtility->executeSql('INSERT INTO `hs...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(30): SchemaIncrementTask59->execute()
#3 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#4 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#8 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#13 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#14 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#15 {main}
2019-Dec-24 08:12:19 : MySQL Error: Table 'xm_hr_symfony.ohrm_marketplace_addon' doesn't exist. 
Query: select * from ohrm_marketplace_addon where plugin_name is not null


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(386): UpgradeUtility->executeSql('select * from o...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(54): UpgradeUtility->getInstalledAddons()
#3 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(15): dbChangeControlAction->getInstalledPlugins()
#4 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#7 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#8 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#9 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#13 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#14 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#15 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#16 {main}
2019-Dec-24 08:12:19 : MySQL Error: Duplicate entry '59' for key 'PRIMARY'. 
Query: INSERT INTO ohrm_upgrade_status
                            (id, status) 
                            VALUES('59' , 'started');


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask.php(63): UpgradeUtility->executeSql('INSERT INTO ohr...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask.php(23): SchemaIncrementTask->createOhrmUpgradeStatus(59)
#3 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask59.php(31): SchemaIncrementTask->execute()
#4 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(30): SchemaIncrementTask59->execute()
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#7 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#8 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#9 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#13 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#14 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#15 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#16 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#17 {main}
2019-Dec-24 08:12:19 : MySQL Error: Incorrect string value: '\xB0S\x03yE0...' for column 'value' at row 1. 
Query: INSERT INTO `hs_hr_config` ( `key`, `value`) VALUES ('csrf_secret', 'I$[_<c°SyE0o‰p’FdQW>Ä-C@¸2a<Ï2l‘+íƒå­ÚSPî"8(€wæ-»K');


StackTrace:#0 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\utility\UpgradeUtility.php(61): UpgradeLogger::writeErrorMessage('2019-Dec-24 08:...', true)
#1 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\schemaIncrementTasks\SchemaIncrementTask59.php(36): UpgradeUtility->executeSql('INSERT INTO `hs...')
#2 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\modules\upgrade\actions\dbChangeControlAction.class.php(30): SchemaIncrementTask59->execute()
#3 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(967): dbChangeControlAction->execute(Object(sfWebRequest))
#4 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(962): sfExecutionFilter->executeAction(Object(dbChangeControlAction))
#5 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(948): sfExecutionFilter->handleAction(Object(sfFilterChain), Object(dbChangeControlAction))
#6 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfExecutionFilter->execute(Object(sfFilterChain))
#7 C:\wamp64\www\orangehrm\upgrader\apps\upgrader\lib\filter\ActionFilter.php(14): sfFilterChain->execute()
#8 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): ActionFilter->execute(Object(sfFilterChain))
#9 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1009): sfFilterChain->execute()
#10 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(1044): sfRenderingFilter->execute(Object(sfFilterChain))
#11 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(685): sfFilterChain->execute()
#12 C:\wamp64\www\orangehrm\upgrader\cache\upgrader\prod\config\config_core_compile.yml.php(2773): sfController->forward('upgrade', 'dbChangeControl')
#13 C:\wamp64\www\orangehrm\symfony\lib\vendor\symfony\lib\util\sfContext.class.php(179): sfFrontWebController->dispatch()
#14 C:\wamp64\www\orangehrm\upgrader\web\index.php(13): sfContext->dispatch()
#15 {main}
```

Seems that some operations are NOT successfully implemented, knowing that my current system (v3.1.1) is working fine.

Appreciate if any idea how to fix the problem, 

Thanks.

**Comment by Damith88** [comment]
Hi Abdul,
thanks for reporting this issue.
I can see 3 issues according to the log you have attached.
We will provide the fixes for these issues in the next release.
for the moment you mat refer to fixes done in development branch.
for the marketplace issue please refer to https://github.com/orangehrm/orangehrm/commit/3c5fc77e3a458fe1db746173330cd43da9480f62
for the csrf issue please refer to https://github.com/Damith88/orangehrm/commit/6a6e27e6b4f06f77fb1a0134b4eb3422fcfd31e3
other issue can be simply fixed by dropping the `ohrm_upgrade_status` table.
sql query: `drop table ohrm_upgrade_status;`
NOTE: the above table is created at the beginning of the upgrade and dropped after upgrade completes successfully.

As I understood from the log you have attached, you can continue the upgrade (without any data loss) if you follow the above mentioned fixes. please take a database dump in case you may want to revert the upgrade.
Hope this information helps you. please let us know if you encounter further issues with upgrade.

**Comment by RajithaKumara** [comment]
Hi @AbdulazizFayez 
Did you successfully run the upgrader?

**Comment by AbdulazizFayez** [comment]
Hi @RajithaKumara 

Since it wasn't successful and had many things on hand.. i haven't tested it out since it wasn't a priority task.

However, i will update here and inform if the upgrade was a success.

**Comment by RajithaKumara** [comment]
Thank you @AbdulazizFayez. Also, you can try later with OrangeHRM 4.3.5 release with fixes, if upgrade not a high priority.

**Comment by kavithagurusamy** [comment]
@AbdulazizFayez 
closing this issue since the 4.3.5 is released with the fix. Please reopen the issue if it doesn't address your scenario.
